-- Metric views for domain: community | Business: Gaming | Version: 1 | Generated on: 2026-05-08 09:42:21

CREATE OR REPLACE VIEW `gaming_ecm`.`_metrics`.`community_support_ticket`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Support ticket resolution, satisfaction, and operational efficiency KPIs for customer service steering"
  source: "`gaming_ecm`.`community`.`support_ticket`"
  dimensions:
    - name: "ticket_status"
      expr: ticket_status
      comment: "Current status of the support ticket (open, closed, pending, etc.)"
    - name: "ticket_priority"
      expr: ticket_priority
      comment: "Priority level assigned to the ticket"
    - name: "issue_category"
      expr: issue_category
      comment: "High-level category of the reported issue"
    - name: "issue_subcategory"
      expr: issue_subcategory
      comment: "Detailed subcategory of the issue"
    - name: "channel"
      expr: channel
      comment: "Channel through which the ticket was submitted (email, chat, phone, etc.)"
    - name: "escalation_tier"
      expr: escalation_tier
      comment: "Escalation tier of the ticket"
    - name: "is_first_contact_resolved"
      expr: is_first_contact_resolved
      comment: "Whether the ticket was resolved on first contact"
    - name: "sla_breach_flag"
      expr: sla_breach_flag
      comment: "Whether the ticket breached SLA targets"
    - name: "bot_handled_flag"
      expr: bot_handled_flag
      comment: "Whether the ticket was handled by automated bot"
    - name: "created_month"
      expr: DATE_TRUNC('MONTH', created_at)
      comment: "Month when the ticket was created"
    - name: "created_week"
      expr: DATE_TRUNC('WEEK', created_at)
      comment: "Week when the ticket was created"
  measures:
    - name: "total_tickets"
      expr: COUNT(1)
      comment: "Total number of support tickets"
    - name: "first_contact_resolution_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_first_contact_resolved = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of tickets resolved on first contact - key efficiency KPI"
    - name: "sla_breach_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN sla_breach_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of tickets that breached SLA - key quality KPI"
    - name: "avg_csat_score"
      expr: AVG(CAST(csat_score AS DOUBLE))
      comment: "Average customer satisfaction score - primary customer experience KPI"
    - name: "bot_automation_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN bot_handled_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of tickets handled by automation - efficiency and cost KPI"
    - name: "avg_reopen_count"
      expr: AVG(CAST(reopen_count AS DOUBLE))
      comment: "Average number of times tickets are reopened - quality indicator"
    - name: "total_comments"
      expr: SUM(CAST(comment_count AS BIGINT))
      comment: "Total number of comments across all tickets - engagement and complexity indicator"
$$;

CREATE OR REPLACE VIEW `gaming_ecm`.`_metrics`.`community_player_report`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Player reporting and moderation effectiveness KPIs for community health and safety steering"
  source: "`gaming_ecm`.`community`.`player_report`"
  dimensions:
    - name: "report_status"
      expr: report_status
      comment: "Current status of the player report"
    - name: "violation_category"
      expr: violation_category
      comment: "Category of the reported violation"
    - name: "violation_subcategory"
      expr: violation_subcategory
      comment: "Detailed subcategory of the violation"
    - name: "severity_level"
      expr: severity_level
      comment: "Severity level of the reported violation"
    - name: "report_source_channel"
      expr: report_source_channel
      comment: "Channel through which the report was submitted"
    - name: "is_automated_flag"
      expr: is_automated_flag
      comment: "Whether the report was generated by automated systems"
    - name: "is_minor_involved"
      expr: is_minor_involved
      comment: "Whether a minor is involved in the incident - regulatory concern"
    - name: "content_rating_concern"
      expr: content_rating_concern
      comment: "Content rating concern flag"
    - name: "submitted_month"
      expr: DATE_TRUNC('MONTH', submitted_timestamp)
      comment: "Month when the report was submitted"
  measures:
    - name: "total_reports"
      expr: COUNT(1)
      comment: "Total number of player reports submitted"
    - name: "avg_resolution_time_hours"
      expr: AVG(CAST(resolution_time_hours AS DOUBLE))
      comment: "Average time to resolve reports in hours - operational efficiency KPI"
    - name: "sla_compliance_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN resolution_time_hours <= sla_target_hours THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of reports resolved within SLA target - service quality KPI"
    - name: "avg_auto_moderation_score"
      expr: AVG(CAST(auto_moderation_score AS DOUBLE))
      comment: "Average automated moderation confidence score - AI effectiveness indicator"
    - name: "automation_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_automated_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of reports handled by automation - efficiency KPI"
    - name: "minor_involvement_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_minor_involved = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of reports involving minors - regulatory risk KPI"
    - name: "repeat_report_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_repeat_report = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of reports that are repeats - moderation effectiveness indicator"
    - name: "avg_evidence_attachments"
      expr: AVG(CAST(evidence_attachment_count AS DOUBLE))
      comment: "Average number of evidence attachments per report - report quality indicator"
$$;

CREATE OR REPLACE VIEW `gaming_ecm`.`_metrics`.`community_ban`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Player ban and enforcement KPIs for community safety and policy compliance steering"
  source: "`gaming_ecm`.`community`.`ban`"
  dimensions:
    - name: "ban_status"
      expr: ban_status
      comment: "Current status of the ban"
    - name: "ban_type"
      expr: ban_type
      comment: "Type of ban applied"
    - name: "ban_scope"
      expr: ban_scope
      comment: "Scope of the ban (game-wide, mode-specific, etc.)"
    - name: "violation_category"
      expr: violation_category
      comment: "Category of violation that triggered the ban"
    - name: "violation_subcategory"
      expr: violation_subcategory
      comment: "Detailed subcategory of the violation"
    - name: "severity_level"
      expr: severity_level
      comment: "Severity level of the violation"
    - name: "is_permanent"
      expr: is_permanent
      comment: "Whether the ban is permanent"
    - name: "is_automated"
      expr: is_automated
      comment: "Whether the ban was applied automatically"
    - name: "is_repeat_offender"
      expr: is_repeat_offender
      comment: "Whether the player is a repeat offender"
    - name: "appeal_status"
      expr: appeal_status
      comment: "Status of any appeal filed against the ban"
    - name: "appeal_outcome"
      expr: appeal_outcome
      comment: "Outcome of the appeal process"
    - name: "created_month"
      expr: DATE_TRUNC('MONTH', created_timestamp)
      comment: "Month when the ban was created"
  measures:
    - name: "total_bans"
      expr: COUNT(1)
      comment: "Total number of bans issued"
    - name: "permanent_ban_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_permanent = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of bans that are permanent - severity indicator"
    - name: "automation_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_automated = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of bans applied automatically - efficiency KPI"
    - name: "repeat_offender_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_repeat_offender = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of bans issued to repeat offenders - recidivism KPI"
    - name: "avg_auto_moderation_score"
      expr: AVG(CAST(auto_moderation_score AS DOUBLE))
      comment: "Average automated moderation confidence score - AI accuracy indicator"
    - name: "avg_prior_ban_count"
      expr: AVG(CAST(prior_ban_count AS DOUBLE))
      comment: "Average number of prior bans per player - repeat behavior indicator"
    - name: "appeal_rate"
      expr: ROUND(100.0 * COUNT(DISTINCT CASE WHEN appeal_status IS NOT NULL THEN ban_id END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of bans that are appealed - fairness perception indicator"
    - name: "minor_involvement_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_minor_involved = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of bans involving minors - regulatory risk KPI"
$$;

CREATE OR REPLACE VIEW `gaming_ecm`.`_metrics`.`community_guild`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Guild engagement, growth, and health KPIs for community ecosystem steering"
  source: "`gaming_ecm`.`community`.`guild`"
  dimensions:
    - name: "guild_status"
      expr: guild_status
      comment: "Current status of the guild"
    - name: "guild_type"
      expr: guild_type
      comment: "Type of guild"
    - name: "privacy_level"
      expr: privacy_level
      comment: "Privacy level of the guild"
    - name: "recruitment_status"
      expr: recruitment_status
      comment: "Whether the guild is actively recruiting"
    - name: "is_verified"
      expr: is_verified
      comment: "Whether the guild is verified"
    - name: "is_esports_org"
      expr: is_esports_org
      comment: "Whether the guild is an esports organization"
    - name: "language_code"
      expr: language_code
      comment: "Primary language of the guild"
    - name: "founded_year"
      expr: YEAR(founded_date)
      comment: "Year the guild was founded"
  measures:
    - name: "total_guilds"
      expr: COUNT(1)
      comment: "Total number of guilds"
    - name: "avg_member_count"
      expr: AVG(CAST(member_count AS DOUBLE))
      comment: "Average number of members per guild - engagement indicator"
    - name: "avg_weekly_active_members"
      expr: AVG(CAST(weekly_active_members AS DOUBLE))
      comment: "Average weekly active members per guild - engagement health KPI"
    - name: "member_activity_rate"
      expr: ROUND(100.0 * AVG(CAST(weekly_active_members AS DOUBLE)) / NULLIF(AVG(CAST(member_count AS DOUBLE)), 0), 2)
      comment: "Percentage of guild members active weekly - engagement quality KPI"
    - name: "avg_nps_score"
      expr: AVG(CAST(nps_score AS DOUBLE))
      comment: "Average Net Promoter Score for guilds - satisfaction KPI"
    - name: "total_guild_xp"
      expr: SUM(CAST(xp_total AS DOUBLE))
      comment: "Total experience points across all guilds - aggregate engagement indicator"
    - name: "avg_guild_xp"
      expr: AVG(CAST(xp_total AS DOUBLE))
      comment: "Average experience points per guild - engagement depth indicator"
    - name: "verified_guild_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_verified = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of guilds that are verified - quality indicator"
    - name: "esports_org_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_esports_org = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of guilds that are esports organizations - competitive ecosystem indicator"
$$;

CREATE OR REPLACE VIEW `gaming_ecm`.`_metrics`.`community_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Community event engagement, satisfaction, and ROI KPIs for live operations steering"
  source: "`gaming_ecm`.`community`.`event`"
  dimensions:
    - name: "event_status"
      expr: event_status
      comment: "Current status of the event"
    - name: "event_type"
      expr: event_type
      comment: "Type of community event"
    - name: "organizer_type"
      expr: organizer_type
      comment: "Type of organizer (official, community, partner, etc.)"
    - name: "is_featured"
      expr: is_featured
      comment: "Whether the event is featured"
    - name: "is_recurring"
      expr: is_recurring
      comment: "Whether the event is recurring"
    - name: "is_age_restricted"
      expr: is_age_restricted
      comment: "Whether the event has age restrictions"
    - name: "prize_type"
      expr: prize_type
      comment: "Type of prize offered"
    - name: "event_month"
      expr: DATE_TRUNC('MONTH', start_timestamp)
      comment: "Month when the event started"
  measures:
    - name: "total_events"
      expr: COUNT(1)
      comment: "Total number of community events"
    - name: "avg_participant_count"
      expr: AVG(CAST(participant_count AS DOUBLE))
      comment: "Average number of participants per event - engagement KPI"
    - name: "avg_registration_count"
      expr: AVG(CAST(registration_count AS DOUBLE))
      comment: "Average number of registrations per event - interest indicator"
    - name: "registration_to_participation_rate"
      expr: ROUND(100.0 * AVG(CAST(participant_count AS DOUBLE)) / NULLIF(AVG(CAST(registration_count AS DOUBLE)), 0), 2)
      comment: "Percentage of registrations that convert to participation - conversion KPI"
    - name: "avg_csat_score"
      expr: AVG(CAST(csat_score AS DOUBLE))
      comment: "Average customer satisfaction score for events - quality KPI"
    - name: "avg_nps_score"
      expr: AVG(CAST(nps_score AS DOUBLE))
      comment: "Average Net Promoter Score for events - loyalty KPI"
    - name: "total_prize_value_usd"
      expr: SUM(CAST(prize_value_usd AS DOUBLE))
      comment: "Total prize value across all events in USD - investment indicator"
    - name: "avg_prize_value_usd"
      expr: AVG(CAST(prize_value_usd AS DOUBLE))
      comment: "Average prize value per event in USD - incentive level indicator"
    - name: "avg_referral_count"
      expr: AVG(CAST(referral_count AS DOUBLE))
      comment: "Average number of referrals per event - viral growth indicator"
    - name: "avg_survey_response_count"
      expr: AVG(CAST(survey_response_count AS DOUBLE))
      comment: "Average survey responses per event - feedback engagement indicator"
$$;

CREATE OR REPLACE VIEW `gaming_ecm`.`_metrics`.`community_ugc_submission`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "User-generated content engagement, monetization, and quality KPIs for creator economy steering"
  source: "`gaming_ecm`.`community`.`ugc_submission`"
  dimensions:
    - name: "submission_status"
      expr: submission_status
      comment: "Current status of the UGC submission"
    - name: "ugc_type"
      expr: ugc_type
      comment: "Type of user-generated content"
    - name: "is_featured"
      expr: is_featured
      comment: "Whether the content is featured"
    - name: "is_monetization_eligible"
      expr: is_monetization_eligible
      comment: "Whether the content is eligible for monetization"
    - name: "is_age_restricted"
      expr: is_age_restricted
      comment: "Whether the content has age restrictions"
    - name: "ip_clearance_status"
      expr: ip_clearance_status
      comment: "Intellectual property clearance status"
    - name: "license_type"
      expr: license_type
      comment: "License type for the content"
    - name: "platform_target"
      expr: platform_target
      comment: "Target platform for the content"
    - name: "published_month"
      expr: DATE_TRUNC('MONTH', published_date)
      comment: "Month when the content was published"
  measures:
    - name: "total_submissions"
      expr: COUNT(1)
      comment: "Total number of UGC submissions"
    - name: "total_downloads"
      expr: SUM(CAST(download_count AS DOUBLE))
      comment: "Total downloads across all UGC - engagement volume KPI"
    - name: "avg_downloads_per_submission"
      expr: AVG(CAST(download_count AS DOUBLE))
      comment: "Average downloads per submission - content popularity KPI"
    - name: "avg_rating_score"
      expr: AVG(CAST(rating_score AS DOUBLE))
      comment: "Average rating score for UGC - quality KPI"
    - name: "avg_rating_count"
      expr: AVG(CAST(rating_count AS DOUBLE))
      comment: "Average number of ratings per submission - engagement depth indicator"
    - name: "avg_comment_count"
      expr: AVG(CAST(comment_count AS DOUBLE))
      comment: "Average comments per submission - community engagement indicator"
    - name: "avg_favorite_count"
      expr: AVG(CAST(favorite_count AS DOUBLE))
      comment: "Average favorites per submission - content affinity indicator"
    - name: "monetization_eligible_rate"
      expr: ROUND(100.0 * SUM(CASE WHEN is_monetization_eligible = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of submissions eligible for monetization - creator economy health KPI"
    - name: "avg_creator_revenue_share_pct"
      expr: AVG(CAST(creator_revenue_share_pct AS DOUBLE))
      comment: "Average creator revenue share percentage - creator incentive indicator"
    - name: "avg_price_virtual_currency"
      expr: AVG(CAST(price_virtual_currency AS DOUBLE))
      comment: "Average price in virtual currency - monetization level indicator"
    - name: "total_file_size_gb"
      expr: SUM(CAST(file_size_bytes AS DOUBLE)) / 1073741824.0
      comment: "Total file size in gigabytes - storage cost indicator"
    - name: "report_rate"
      expr: ROUND(100.0 * AVG(CAST(report_count AS DOUBLE)) / NULLIF(AVG(CAST(download_count AS DOUBLE)), 0) * 100, 2)
      comment: "Reports per 100 downloads - content safety KPI"
$$;

CREATE OR REPLACE VIEW `gaming_ecm`.`_metrics`.`community_forum`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Forum engagement, growth, and health KPIs for community platform steering"
  source: "`gaming_ecm`.`community`.`forum`"
  dimensions:
    - name: "forum_status"
      expr: forum_status
      comment: "Current status of the forum"
    - name: "forum_type"
      expr: forum_type
      comment: "Type of forum"
    - name: "forum_category"
      expr: forum_category
      comment: "Category of the forum"
    - name: "visibility"
      expr: visibility
      comment: "Visibility level of the forum"
    - name: "moderation_mode"
      expr: moderation_mode
      comment: "Moderation mode applied to the forum"
    - name: "is_featured"
      expr: is_featured
      comment: "Whether the forum is featured"
    - name: "is_age_restricted"
      expr: is_age_restricted
      comment: "Whether the forum has age restrictions"
    - name: "locale_code"
      expr: locale_code
      comment: "Locale code for the forum"
  measures:
    - name: "total_forums"
      expr: COUNT(1)
      comment: "Total number of forums"
    - name: "total_threads"
      expr: SUM(CAST(thread_count AS DOUBLE))
      comment: "Total number of threads across all forums - content volume KPI"
    - name: "total_posts"
      expr: SUM(CAST(post_count AS DOUBLE))
      comment: "Total number of posts across all forums - engagement volume KPI"
    - name: "total_subscribers"
      expr: SUM(CAST(subscriber_count AS DOUBLE))
      comment: "Total subscribers across all forums - audience size KPI"
    - name: "avg_threads_per_forum"
      expr: AVG(CAST(thread_count AS DOUBLE))
      comment: "Average threads per forum - content density indicator"
    - name: "avg_posts_per_forum"
      expr: AVG(CAST(post_count AS DOUBLE))
      comment: "Average posts per forum - engagement density indicator"
    - name: "avg_subscribers_per_forum"
      expr: AVG(CAST(subscriber_count AS DOUBLE))
      comment: "Average subscribers per forum - audience reach indicator"
    - name: "posts_per_thread_ratio"
      expr: ROUND(SUM(CAST(post_count AS DOUBLE)) / NULLIF(SUM(CAST(thread_count AS DOUBLE)), 0), 2)
      comment: "Average posts per thread - discussion depth KPI"
    - name: "avg_csat_score"
      expr: AVG(CAST(csat_score AS DOUBLE))
      comment: "Average customer satisfaction score for forums - quality KPI"
    - name: "avg_nps_score"
      expr: AVG(CAST(nps_score AS DOUBLE))
      comment: "Average Net Promoter Score for forums - loyalty KPI"
    - name: "avg_dau"
      expr: AVG(CAST(dau AS DOUBLE))
      comment: "Average daily active users per forum - engagement frequency indicator"
    - name: "avg_mau"
      expr: AVG(CAST(mau AS DOUBLE))
      comment: "Average monthly active users per forum - engagement reach indicator"
$$;