-- Schema for Domain: shared | Business: Apparel Fashion | Version: v1_ecm
-- Generated on: 2026-05-05 15:54:38

-- ========= DATABASE =========
CREATE DATABASE IF NOT EXISTS `apparel_fashion_ecm`.`shared` COMMENT 'Shared domain (auto-created for table organization)';

-- ========= TABLES =========
CREATE OR REPLACE TABLE `apparel_fashion_ecm`.`shared`.`organization` (
    `organization_id` BIGINT COMMENT 'Primary key for organization',
    `address_line_1` STRING COMMENT 'The first line of the organizations primary physical address, typically including street number and name.',
    `address_line_2` STRING COMMENT 'The second line of the organizations primary physical address, typically including suite, floor, or building information.',
    `annual_revenue_amount` DECIMAL(18,2) COMMENT 'The total annual revenue generated by the organization in the base currency.',
    `city` STRING COMMENT 'The city or municipality where the organization is located.',
    `country_code` STRING COMMENT 'The ISO 3166-1 alpha-3 country code where the organization is located.',
    `created_timestamp` TIMESTAMP COMMENT 'The timestamp when this organization record was first created in the system.',
    `credit_rating` STRING COMMENT 'The credit rating assigned to the organization by a recognized credit rating agency.',
    `currency_code` STRING COMMENT 'The ISO 4217 three-letter currency code used for financial reporting by the organization.',
    `dissolution_date` DATE COMMENT 'The date on which the organization was legally dissolved or ceased operations, if applicable.',
    `doing_business_as_name` STRING COMMENT 'The trade name or brand name under which the organization operates, if different from the legal name.',
    `duns_number` STRING COMMENT 'The nine-digit DUNS number assigned by Dun & Bradstreet to uniquely identify the organization.',
    `effective_date` DATE COMMENT 'The date from which this organization record becomes effective in the system.',
    `employee_count` STRING COMMENT 'The total number of employees working for the organization.',
    `expiration_date` DATE COMMENT 'The date on which this organization record expires or is no longer valid, if applicable.',
    `fiscal_year_end_month` STRING COMMENT 'The month (1-12) in which the organizations fiscal year ends.',
    `incorporation_date` DATE COMMENT 'The date on which the organization was legally incorporated or established.',
    `industry_classification_code` STRING COMMENT 'The standard industry classification code (e.g., NAICS, SIC) that categorizes the organizations primary business activity.',
    `is_publicly_traded` BOOLEAN COMMENT 'Indicates whether the organization is publicly traded on a stock exchange.',
    `is_tax_exempt` BOOLEAN COMMENT 'Indicates whether the organization has tax-exempt status.',
    `last_modified_timestamp` TIMESTAMP COMMENT 'The timestamp when this organization record was last updated or modified.',
    `legal_entity_identifier` STRING COMMENT 'The ISO 17442 Legal Entity Identifier for the organization, a 20-character alphanumeric code.',
    `organization_name` STRING COMMENT 'The legal or registered name of the organization.',
    `notes` STRING COMMENT 'Additional free-form notes or comments about the organization.',
    `organization_type` STRING COMMENT 'The classification of the organization based on its structural role within the enterprise.',
    `parent_organization_id` BIGINT COMMENT 'Reference to the parent organization if this organization is a subsidiary or branch.',
    `postal_code` STRING COMMENT 'The postal or ZIP code for the organizations primary address.',
    `primary_business_description` STRING COMMENT 'A textual description of the organizations primary business activities and operations.',
    `primary_contact_email` STRING COMMENT 'The primary email address for contacting the organization.',
    `primary_contact_phone` STRING COMMENT 'The primary phone number for contacting the organization.',
    `registration_authority` STRING COMMENT 'The name of the government or regulatory body that issued the registration number.',
    `registration_number` STRING COMMENT 'The official registration or company number assigned by the government or regulatory authority.',
    `state_province` STRING COMMENT 'The state, province, or region where the organization is located.',
    `organization_status` STRING COMMENT 'The current operational status of the organization within the enterprise.',
    `stock_exchange_symbol` STRING COMMENT 'The ticker symbol under which the organizations stock is traded on a public exchange, if applicable.',
    `tax_identification_number` STRING COMMENT 'The tax identification number assigned by the relevant tax authority for the organization.',
    `time_zone` STRING COMMENT 'The IANA time zone identifier for the organizations primary location.',
    `website_url` STRING COMMENT 'The official website URL of the organization.',
    CONSTRAINT pk_organization PRIMARY KEY(`organization_id`)
) COMMENT 'Master reference table for organization. Referenced by organization_id.';

-- ========= TAGS =========
ALTER SCHEMA `apparel_fashion_ecm`.`shared` SET TAGS ('dbx_division' = 'operations');
ALTER SCHEMA `apparel_fashion_ecm`.`shared` SET TAGS ('dbx_domain' = 'shared');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` SET TAGS ('dbx_data_type' = 'master_data');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `organization_id` SET TAGS ('dbx_business_glossary_term' = 'Organization Identifier');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `address_line_1` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `address_line_1` SET TAGS ('dbx_pii_address' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `address_line_2` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `address_line_2` SET TAGS ('dbx_pii_address' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `annual_revenue_amount` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `city` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `city` SET TAGS ('dbx_pii_address' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `credit_rating` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `postal_code` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `postal_code` SET TAGS ('dbx_pii_address' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `primary_contact_email` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `primary_contact_email` SET TAGS ('dbx_pii_email' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `primary_contact_phone` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `primary_contact_phone` SET TAGS ('dbx_pii_phone' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `state_province` SET TAGS ('dbx_confidential' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `state_province` SET TAGS ('dbx_pii_address' = 'true');
ALTER TABLE `apparel_fashion_ecm`.`shared`.`organization` ALTER COLUMN `tax_identification_number` SET TAGS ('dbx_confidential' = 'true');
