-- Metric views for domain: menu | Business: Restaurants | Version: 1 | Generated on: 2026-05-06 03:57:03

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_pmix_record`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Product mix (PMIX) performance metrics tracking sales volume, revenue, margin, and menu engineering classification across menu items, dayparts, channels, and restaurant formats. Core KPI layer for menu profitability and mix management decisions."
  source: "`restaurants_ecm`.`menu`.`pmix_record`"
  dimensions:
    - name: "reporting_date"
      expr: reporting_date
      comment: "Date of the PMIX record, used for time-series trending of menu item performance."
    - name: "reporting_period_type"
      expr: reporting_period_type
      comment: "Granularity of the reporting period (e.g., daily, weekly, period) for aggregation control."
    - name: "daypart"
      expr: daypart
      comment: "Meal period (e.g., breakfast, lunch, dinner, late night) enabling daypart-level menu performance analysis."
    - name: "sales_channel"
      expr: sales_channel
      comment: "Order channel (e.g., dine-in, drive-thru, OLO, 3PD) for channel-mix revenue attribution."
    - name: "restaurant_format"
      expr: restaurant_format
      comment: "Restaurant format (e.g., QSR, casual, fine-dining) for format-level menu benchmarking."
    - name: "menu_engineering_classification"
      expr: menu_engineering_classification
      comment: "Menu engineering quadrant (Star, Plow Horse, Puzzle, Dog) used to classify items by popularity and profitability."
    - name: "menu_category"
      expr: menu_category
      comment: "High-level menu category (e.g., Burgers, Beverages, Sides) for category-level performance rollups."
    - name: "ownership_type"
      expr: ownership_type
      comment: "Franchise vs. company-owned designation for ownership-model performance comparison."
    - name: "is_lto"
      expr: is_lto
      comment: "Flag indicating whether the item is a Limited Time Offer, enabling LTO vs. core menu performance comparison."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the financial amounts for multi-currency reporting normalization."
  measures:
    - name: "total_gross_sales"
      expr: SUM(CAST(gross_sales_amount AS DOUBLE))
      comment: "Total gross sales revenue before discounts, voids, and refunds. Primary top-line revenue KPI for menu performance."
    - name: "total_net_sales"
      expr: SUM(CAST(net_sales_amount AS DOUBLE))
      comment: "Total net sales after discounts and voids. Core revenue measure used in P&L and menu profitability reporting."
    - name: "total_cogs"
      expr: SUM(CAST(cogs_amount AS DOUBLE))
      comment: "Total cost of goods sold across all menu items sold. Directly drives gross margin and food cost management decisions."
    - name: "total_contribution_margin"
      expr: SUM(CAST(contribution_margin_amount AS DOUBLE))
      comment: "Total contribution margin (net sales minus COGS) generated by menu items. Key profitability KPI for menu engineering."
    - name: "total_discount_amount"
      expr: SUM(CAST(discount_amount AS DOUBLE))
      comment: "Total discounts applied across menu items. Tracks promotional spend impact on revenue realization."
    - name: "total_void_amount"
      expr: SUM(CAST(void_amount AS DOUBLE))
      comment: "Total voided transaction value. Elevated void amounts signal operational or POS integrity issues requiring investigation."
    - name: "total_refund_amount"
      expr: SUM(CAST(refund_amount AS DOUBLE))
      comment: "Total refund value issued. Tracks guest dissatisfaction and quality issues at the menu item level."
    - name: "total_comp_amount"
      expr: SUM(CAST(comp_amount AS DOUBLE))
      comment: "Total complimentary (comped) item value. Monitors hospitality spend and exception management by menu item."
    - name: "avg_selling_price"
      expr: AVG(CAST(avg_selling_price AS DOUBLE))
      comment: "Average realized selling price per menu item record. Tracks price realization vs. list price across channels and formats."
    - name: "avg_cogs_pct"
      expr: AVG(CAST(cogs_pct AS DOUBLE))
      comment: "Average cost of goods sold percentage. Core food cost efficiency KPI; deviations from target trigger menu re-engineering."
    - name: "avg_menu_mix_pct"
      expr: AVG(CAST(menu_mix_pct AS DOUBLE))
      comment: "Average menu mix percentage showing each item's share of total item count sold. Drives menu simplification and focus decisions."
    - name: "avg_sales_mix_pct"
      expr: AVG(CAST(sales_mix_pct AS DOUBLE))
      comment: "Average sales mix percentage showing each item's share of total revenue. Identifies revenue-concentration risk in the menu portfolio."
    - name: "total_unavailability_hours"
      expr: SUM(CAST(unavailability_hours AS DOUBLE))
      comment: "Total hours a menu item was unavailable (86'd or suppressed). Quantifies lost sales opportunity and operational reliability."
    - name: "distinct_menu_items_sold"
      expr: COUNT(DISTINCT menu_item_id)
      comment: "Count of distinct menu items with sales activity. Measures effective menu breadth and identifies dormant SKUs."
    - name: "distinct_units_with_sales"
      expr: COUNT(DISTINCT unit_id)
      comment: "Count of distinct restaurant units contributing to PMIX records. Used for coverage and rollout completeness analysis."
    - name: "contribution_margin_rate"
      expr: ROUND(100.0 * SUM(CAST(contribution_margin_amount AS DOUBLE)) / NULLIF(SUM(CAST(net_sales_amount AS DOUBLE)), 0), 2)
      comment: "Contribution margin as a percentage of net sales. Composite profitability rate KPI used in menu engineering quadrant analysis."
    - name: "discount_rate"
      expr: ROUND(100.0 * SUM(CAST(discount_amount AS DOUBLE)) / NULLIF(SUM(CAST(gross_sales_amount AS DOUBLE)), 0), 2)
      comment: "Discount amount as a percentage of gross sales. Measures promotional intensity and its drag on revenue realization."
    - name: "void_rate"
      expr: ROUND(100.0 * SUM(CAST(void_amount AS DOUBLE)) / NULLIF(SUM(CAST(gross_sales_amount AS DOUBLE)), 0), 2)
      comment: "Void amount as a percentage of gross sales. Operational quality KPI; high void rates indicate POS errors or training gaps."
    - name: "refund_rate"
      expr: ROUND(100.0 * SUM(CAST(refund_amount AS DOUBLE)) / NULLIF(SUM(CAST(net_sales_amount AS DOUBLE)), 0), 2)
      comment: "Refund amount as a percentage of net sales. Guest satisfaction proxy; elevated refund rates trigger quality and service investigations."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_item_cost`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Menu item cost and margin metrics tracking theoretical vs. actual food cost, waste, yield, and cost variance by item, channel, daypart, and restaurant format. Drives food cost management, recipe optimization, and pricing strategy."
  source: "`restaurants_ecm`.`menu`.`item_cost`"
  dimensions:
    - name: "cost_calculation_date"
      expr: cost_calculation_date
      comment: "Date the cost was calculated, enabling time-series tracking of cost trends and inflation impact."
    - name: "effective_start_date"
      expr: effective_start_date
      comment: "Start date of the cost record's validity window for point-in-time cost analysis."
    - name: "channel"
      expr: channel
      comment: "Sales channel (e.g., dine-in, drive-thru, delivery) for channel-specific cost structure analysis."
    - name: "daypart"
      expr: daypart
      comment: "Meal period for daypart-level cost and margin analysis."
    - name: "restaurant_format"
      expr: restaurant_format
      comment: "Restaurant format for format-level food cost benchmarking."
    - name: "menu_engineering_class"
      expr: menu_engineering_class
      comment: "Menu engineering classification for cost analysis by item profitability tier."
    - name: "cost_calculation_method"
      expr: cost_calculation_method
      comment: "Method used to calculate cost (e.g., standard, actual, theoretical) for methodology-level cost comparison."
    - name: "cost_status"
      expr: cost_status
      comment: "Approval/lifecycle status of the cost record (e.g., approved, pending, superseded)."
    - name: "is_lto"
      expr: is_lto
      comment: "Flag for Limited Time Offer items to compare LTO vs. core menu cost structures."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of cost amounts for multi-currency normalization."
  measures:
    - name: "avg_theoretical_cogs_pct"
      expr: AVG(CAST(theoretical_cogs_pct AS DOUBLE))
      comment: "Average theoretical (recipe-based) cost of goods sold percentage. Baseline food cost target used in menu pricing and engineering."
    - name: "avg_actual_cogs_pct"
      expr: AVG(CAST(actual_cogs_pct AS DOUBLE))
      comment: "Average actual realized COGS percentage. Compared against theoretical to identify waste, theft, or portioning issues."
    - name: "avg_target_cogs_pct"
      expr: AVG(CAST(target_cogs_pct AS DOUBLE))
      comment: "Average target COGS percentage set by finance/operations. Benchmark for evaluating actual vs. planned food cost performance."
    - name: "avg_cogs_pct_variance"
      expr: AVG(CAST(cogs_pct_variance AS DOUBLE))
      comment: "Average variance between actual and target COGS percentage. Negative variance signals over-cost items requiring corrective action."
    - name: "total_theoretical_cost_amount"
      expr: SUM(CAST(theoretical_cost_amount AS DOUBLE))
      comment: "Total theoretical cost amount across all item cost records. Used to benchmark actual spend against recipe-based expectations."
    - name: "total_theoretical_cost_variance"
      expr: SUM(CAST(theoretical_cost_variance_amount AS DOUBLE))
      comment: "Total variance between theoretical and actual cost amounts. Quantifies the financial impact of food cost inefficiencies."
    - name: "total_packaging_cost"
      expr: SUM(CAST(packaging_cost AS DOUBLE))
      comment: "Total packaging cost across menu items. Tracks non-food COGS component for total cost-of-sale analysis."
    - name: "total_primary_protein_cost"
      expr: SUM(CAST(primary_protein_cost AS DOUBLE))
      comment: "Total primary protein cost — the largest and most volatile food cost component. Critical for commodity risk and menu pricing decisions."
    - name: "avg_base_selling_price"
      expr: AVG(CAST(base_selling_price AS DOUBLE))
      comment: "Average base selling price across item cost records. Used to compute implied margin and validate pricing vs. cost structure."
    - name: "avg_waste_pct"
      expr: AVG(CAST(waste_pct AS DOUBLE))
      comment: "Average waste percentage across menu items. Elevated waste drives food cost overruns and sustainability concerns."
    - name: "avg_yield_pct"
      expr: AVG(CAST(yield_pct AS DOUBLE))
      comment: "Average yield percentage (usable output per unit of input). Low yield signals prep inefficiency or ingredient quality issues."
    - name: "avg_cost_per_gram"
      expr: AVG(CAST(cost_per_gram AS DOUBLE))
      comment: "Average cost per gram of menu item. Enables normalized cost comparison across items of different portion sizes."
    - name: "avg_portion_size_grams"
      expr: AVG(CAST(portion_size_grams AS DOUBLE))
      comment: "Average portion size in grams. Tracks portion consistency and its impact on food cost and guest value perception."
    - name: "theoretical_vs_actual_cogs_gap"
      expr: ROUND(AVG(CAST(actual_cogs_pct AS DOUBLE)) - AVG(CAST(theoretical_cogs_pct AS DOUBLE)), 2)
      comment: "Gap between average actual and theoretical COGS percentage. Positive gap indicates systemic over-cost vs. recipe standard — a key operational efficiency KPI."
    - name: "distinct_items_costed"
      expr: COUNT(DISTINCT menu_item_id)
      comment: "Count of distinct menu items with active cost records. Measures cost governance coverage across the menu portfolio."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_item_price`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Menu item pricing metrics tracking base price, promotional pricing, channel surcharges, franchise price deviation, and price elasticity positioning. Supports pricing strategy, franchise compliance, and revenue optimization decisions."
  source: "`restaurants_ecm`.`menu`.`item_price`"
  dimensions:
    - name: "effective_start_date"
      expr: effective_start_date
      comment: "Price effective start date for point-in-time and trend pricing analysis."
    - name: "effective_end_date"
      expr: effective_end_date
      comment: "Price effective end date for identifying expired or expiring price records."
    - name: "daypart"
      expr: daypart
      comment: "Meal period for daypart-specific pricing analysis (e.g., breakfast value pricing vs. dinner premium)."
    - name: "ordering_channel"
      expr: ordering_channel
      comment: "Channel through which the price applies (e.g., in-store, OLO, 3PD) for channel surcharge and pricing strategy analysis."
    - name: "restaurant_format"
      expr: restaurant_format
      comment: "Restaurant format for format-level price benchmarking and consistency audits."
    - name: "ownership_type"
      expr: ownership_type
      comment: "Franchise vs. company-owned for franchise price compliance monitoring."
    - name: "menu_engineering_category"
      expr: menu_engineering_category
      comment: "Menu engineering tier for price-by-profitability-class analysis."
    - name: "price_elasticity_band"
      expr: price_elasticity_band
      comment: "Price elasticity classification (e.g., elastic, inelastic) for demand-sensitive pricing decisions."
    - name: "is_lto"
      expr: is_lto
      comment: "Flag for Limited Time Offer pricing to compare LTO vs. core menu price structures."
    - name: "is_active"
      expr: is_active
      comment: "Active price record flag for filtering to currently effective prices."
    - name: "country_code"
      expr: country_code
      comment: "Country for international price benchmarking and local market pricing analysis."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of price amounts for multi-currency normalization."
  measures:
    - name: "avg_base_price"
      expr: AVG(CAST(base_price AS DOUBLE))
      comment: "Average base menu price across items and markets. Core pricing KPI for competitive benchmarking and price architecture reviews."
    - name: "avg_suggested_retail_price"
      expr: AVG(CAST(suggested_retail_price AS DOUBLE))
      comment: "Average suggested retail price. Compared against base price to measure price realization and franchisee compliance."
    - name: "avg_promotional_price"
      expr: AVG(CAST(promotional_price AS DOUBLE))
      comment: "Average promotional price across active promotions. Tracks depth of promotional discounting and its impact on revenue."
    - name: "avg_channel_surcharge"
      expr: AVG(CAST(channel_surcharge AS DOUBLE))
      comment: "Average channel surcharge applied (e.g., delivery upcharge). Monitors channel economics and guest price perception."
    - name: "avg_cogs_pct"
      expr: AVG(CAST(cogs_pct AS DOUBLE))
      comment: "Average COGS percentage at the price record level. Validates that pricing maintains target food cost margins."
    - name: "avg_cost_of_goods"
      expr: AVG(CAST(cost_of_goods AS DOUBLE))
      comment: "Average cost of goods per item price record. Used to compute implied gross margin at the item-price level."
    - name: "avg_franchise_price_deviation_pct"
      expr: AVG(CAST(franchise_price_deviation_pct AS DOUBLE))
      comment: "Average percentage deviation of franchise prices from the suggested retail price. Franchise compliance KPI; large deviations trigger brand pricing audits."
    - name: "avg_price_override_limit"
      expr: AVG(CAST(price_override_limit AS DOUBLE))
      comment: "Average maximum price override limit granted. Tracks pricing flexibility governance across franchise and company-owned units."
    - name: "distinct_items_priced"
      expr: COUNT(DISTINCT menu_item_id)
      comment: "Count of distinct menu items with active price records. Measures pricing governance coverage across the menu portfolio."
    - name: "distinct_units_with_prices"
      expr: COUNT(DISTINCT unit_id)
      comment: "Count of distinct restaurant units with price records. Used for pricing rollout completeness and compliance audits."
    - name: "promo_vs_base_price_discount_rate"
      expr: ROUND(100.0 * (AVG(CAST(base_price AS DOUBLE)) - AVG(CAST(promotional_price AS DOUBLE))) / NULLIF(AVG(CAST(base_price AS DOUBLE)), 0), 2)
      comment: "Average promotional discount depth as a percentage of base price. Measures promotional intensity and its revenue dilution impact."
    - name: "srp_vs_base_price_gap"
      expr: ROUND(AVG(CAST(suggested_retail_price AS DOUBLE)) - AVG(CAST(base_price AS DOUBLE)), 2)
      comment: "Average gap between suggested retail price and base price. Positive gap indicates upward pricing headroom; negative signals pricing below recommendation."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_lto`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Limited Time Offer (LTO) lifecycle and performance metrics tracking launch timing, food cost targets, rollout scope, approval status, and market coverage. Supports LTO pipeline management, innovation ROI, and promotional strategy decisions."
  source: "`restaurants_ecm`.`menu`.`menu_lto`"
  dimensions:
    - name: "planned_launch_date"
      expr: planned_launch_date
      comment: "Planned launch date for LTO pipeline scheduling and lead-time analysis."
    - name: "actual_launch_date"
      expr: actual_launch_date
      comment: "Actual launch date for on-time launch performance tracking."
    - name: "lifecycle_status"
      expr: lifecycle_status
      comment: "Current lifecycle stage of the LTO (e.g., concept, approved, active, retired) for pipeline stage-gate reporting."
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of the LTO for governance and compliance tracking."
    - name: "lto_type"
      expr: lto_type
      comment: "Type of LTO (e.g., seasonal, promotional, test) for portfolio mix analysis."
    - name: "rollout_scope"
      expr: rollout_scope
      comment: "Geographic or unit scope of the LTO rollout (e.g., national, regional, test market)."
    - name: "daypart"
      expr: daypart
      comment: "Target daypart for the LTO for daypart innovation portfolio analysis."
    - name: "restaurant_format"
      expr: restaurant_format
      comment: "Restaurant format applicability for format-level LTO performance comparison."
    - name: "is_national_launch"
      expr: is_national_launch
      comment: "Flag for national vs. regional/test LTO launches for scale and investment analysis."
    - name: "is_returning_item"
      expr: is_returning_item
      comment: "Flag for returning LTO items vs. new innovations for portfolio novelty tracking."
    - name: "season_or_occasion"
      expr: season_or_occasion
      comment: "Season or occasion driving the LTO (e.g., summer, holiday) for seasonal portfolio planning."
    - name: "country_code"
      expr: country_code
      comment: "Country of LTO deployment for international innovation portfolio management."
  measures:
    - name: "total_lto_count"
      expr: COUNT(1)
      comment: "Total number of LTO records. Tracks innovation pipeline volume and cadence of new item introductions."
    - name: "avg_target_food_cost_pct"
      expr: AVG(CAST(target_food_cost_pct AS DOUBLE))
      comment: "Average target food cost percentage for LTO items. Ensures new items are designed within acceptable margin thresholds before launch."
    - name: "avg_suggested_retail_price"
      expr: AVG(CAST(suggested_retail_price AS DOUBLE))
      comment: "Average suggested retail price for LTO items. Tracks LTO price positioning relative to core menu and competitive set."
    - name: "avg_pmix_target_pct"
      expr: AVG(CAST(pmix_target_pct AS DOUBLE))
      comment: "Average product mix target percentage for LTO items. Measures ambition of LTO volume targets and informs marketing investment sizing."
    - name: "avg_launch_lead_time_days"
      expr: AVG(CAST(launch_lead_time_days AS DOUBLE))
      comment: "Average lead time in days from concept to launch. Operational efficiency KPI for the LTO development pipeline; long lead times signal process bottlenecks."
    - name: "avg_planned_duration_days"
      expr: AVG(CAST(planned_duration_days AS DOUBLE))
      comment: "Average planned duration in days for LTO items. Informs promotional calendar planning and supply chain commitment windows."
    - name: "launch_on_time_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN actual_launch_date <= planned_launch_date THEN 1 END) / NULLIF(COUNT(CASE WHEN actual_launch_date IS NOT NULL AND planned_launch_date IS NOT NULL THEN 1 END), 0), 2)
      comment: "Percentage of LTOs launched on or before the planned launch date. Operational excellence KPI for the innovation pipeline; low rates indicate systemic execution gaps."
    - name: "food_safety_approval_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN food_safety_approved = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of LTO items with food safety approval. Compliance KPI; any gap below 100% for active LTOs is a critical risk requiring immediate escalation."
    - name: "nutritional_approval_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN nutritional_approved = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of LTO items with nutritional approval. Regulatory compliance KPI for menu labeling requirements."
    - name: "allergen_review_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN allergen_reviewed = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of LTO items with completed allergen review. Guest safety compliance KPI; gaps expose the brand to allergen incident liability."
    - name: "national_launch_pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_national_launch = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of LTOs designated as national launches. Measures scale of innovation investment and national vs. local promotional strategy balance."
    - name: "returning_item_pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_returning_item = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of LTOs that are returning (previously launched) items. High rates indicate reliance on proven items vs. true innovation investment."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_item_86_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Item 86 (out-of-stock/unavailability) event metrics tracking frequency, duration, food safety linkage, and operational impact of menu item unavailability events. Drives inventory reliability, guest experience, and operational risk management decisions."
  source: "`restaurants_ecm`.`menu`.`item_86_event`"
  dimensions:
    - name: "start_timestamp"
      expr: start_timestamp
      comment: "Timestamp when the 86 event began, used for time-series analysis of unavailability patterns."
    - name: "daypart_affected"
      expr: daypart_affected
      comment: "Daypart during which the item was unavailable, identifying peak-period availability failures."
    - name: "reason_code"
      expr: reason_code
      comment: "Root cause code for the 86 event (e.g., out of stock, equipment failure, recall) for cause-based operational analysis."
    - name: "event_status"
      expr: event_status
      comment: "Current status of the 86 event (e.g., open, resolved, escalated) for active issue management."
    - name: "restaurant_format"
      expr: restaurant_format
      comment: "Restaurant format for format-level availability reliability benchmarking."
    - name: "ownership_model"
      expr: ownership_model
      comment: "Franchise vs. company-owned for ownership-model availability performance comparison."
    - name: "is_food_safety_related"
      expr: is_food_safety_related
      comment: "Flag for food safety-driven 86 events, enabling separation of safety-critical unavailability from operational stockouts."
    - name: "is_recall_related"
      expr: is_recall_related
      comment: "Flag for recall-driven 86 events. Recall-related events require immediate escalation and regulatory reporting."
    - name: "is_lto_item"
      expr: is_lto_item
      comment: "Flag for LTO items being 86'd, which has amplified guest impact due to promotional expectations."
    - name: "olo_suppressed"
      expr: olo_suppressed
      comment: "Flag indicating the item was suppressed on the OLO (online ordering) platform during the event."
    - name: "pos_suppressed"
      expr: pos_suppressed
      comment: "Flag indicating the item was suppressed on the POS during the event."
  measures:
    - name: "total_86_events"
      expr: COUNT(1)
      comment: "Total number of item 86 events. Primary availability reliability KPI; high event counts signal systemic supply or operational failures."
    - name: "distinct_items_86d"
      expr: COUNT(DISTINCT primary_menu_item_id)
      comment: "Count of distinct menu items that experienced at least one 86 event. Measures breadth of menu availability risk across the portfolio."
    - name: "distinct_units_with_86_events"
      expr: COUNT(DISTINCT unit_id)
      comment: "Count of distinct restaurant units with 86 events. Identifies units with systemic availability problems requiring targeted intervention."
    - name: "food_safety_86_event_count"
      expr: COUNT(CASE WHEN is_food_safety_related = TRUE THEN 1 END)
      comment: "Count of 86 events driven by food safety concerns. Critical risk KPI; any food safety-related unavailability requires immediate investigation and reporting."
    - name: "recall_related_86_event_count"
      expr: COUNT(CASE WHEN is_recall_related = TRUE THEN 1 END)
      comment: "Count of 86 events triggered by ingredient or product recalls. Regulatory and brand risk KPI requiring executive visibility."
    - name: "avg_event_duration_minutes"
      expr: AVG(CAST(duration_minutes AS DOUBLE))
      comment: "Average duration of 86 events in minutes. Longer durations indicate slower resolution and greater guest impact and lost sales exposure."
    - name: "guest_notification_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN guest_notification_sent = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of 86 events where guests were proactively notified. Guest experience KPI; low notification rates during high-impact events damage brand trust."
    - name: "escalation_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN escalated_to_team IS NOT NULL THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of 86 events that were escalated to a support team. Measures severity distribution and operational response capability."
    - name: "olo_suppression_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN olo_suppressed = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of 86 events where the item was suppressed on OLO. Tracks digital channel availability management during stockout events."
    - name: "food_safety_86_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_food_safety_related = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of all 86 events that are food safety-related. Composite risk KPI; elevated rates signal systemic food safety supply chain vulnerabilities."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_recipe`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Recipe portfolio metrics tracking food cost, nutritional profile, yield, waste, and food safety compliance across the recipe library. Supports recipe standardization, cost optimization, and regulatory compliance decisions."
  source: "`restaurants_ecm`.`menu`.`recipe`"
  dimensions:
    - name: "effective_date"
      expr: effective_date
      comment: "Date the recipe version became effective for point-in-time recipe analysis."
    - name: "recipe_category"
      expr: recipe_category
      comment: "High-level recipe category (e.g., proteins, sides, beverages) for category-level cost and nutrition analysis."
    - name: "recipe_type"
      expr: recipe_type
      comment: "Recipe type (e.g., core, LTO, test) for portfolio segmentation."
    - name: "recipe_status"
      expr: recipe_status
      comment: "Lifecycle status of the recipe (e.g., active, retired, in-development) for governance and compliance tracking."
    - name: "cook_method"
      expr: cook_method
      comment: "Cooking method (e.g., fried, grilled, baked) for operational equipment planning and energy cost analysis."
    - name: "daypart"
      expr: daypart
      comment: "Target daypart for the recipe for daypart-level cost and nutrition portfolio analysis."
    - name: "restaurant_format"
      expr: restaurant_format
      comment: "Restaurant format applicability for format-level recipe standardization analysis."
    - name: "is_gluten_free"
      expr: is_gluten_free
      comment: "Gluten-free certification flag for dietary accommodation portfolio tracking."
    - name: "is_vegan"
      expr: is_vegan
      comment: "Vegan flag for plant-based portfolio analysis and menu diversification tracking."
    - name: "is_vegetarian"
      expr: is_vegetarian
      comment: "Vegetarian flag for dietary accommodation portfolio tracking."
    - name: "haccp_ccp_flag"
      expr: haccp_ccp_flag
      comment: "Flag indicating the recipe has a HACCP critical control point. Food safety compliance dimension for regulatory audit readiness."
  measures:
    - name: "total_active_recipes"
      expr: COUNT(1)
      comment: "Total number of recipe records. Tracks recipe library size and complexity for operational standardization management."
    - name: "avg_food_cost"
      expr: AVG(CAST(food_cost AS DOUBLE))
      comment: "Average food cost per recipe. Core cost management KPI for recipe portfolio profitability analysis."
    - name: "avg_food_cost_pct"
      expr: AVG(CAST(food_cost_pct AS DOUBLE))
      comment: "Average food cost as a percentage of menu price. Primary recipe profitability KPI; deviations from target trigger recipe re-engineering."
    - name: "avg_menu_price"
      expr: AVG(CAST(menu_price AS DOUBLE))
      comment: "Average menu price across recipes. Used to benchmark recipe pricing against cost structure and competitive positioning."
    - name: "avg_calories"
      expr: AVG(CAST(calories AS DOUBLE))
      comment: "Average calorie count per recipe. Nutritional portfolio KPI for health and wellness strategy and regulatory menu labeling compliance."
    - name: "avg_sodium_mg"
      expr: AVG(CAST(sodium_mg AS DOUBLE))
      comment: "Average sodium content in milligrams per recipe. Health and regulatory KPI; high sodium levels attract regulatory scrutiny and guest health concerns."
    - name: "avg_waste_pct"
      expr: AVG(CAST(waste_pct AS DOUBLE))
      comment: "Average waste percentage across recipes. Sustainability and cost KPI; high waste drives food cost overruns and ESG reporting concerns."
    - name: "avg_yield_quantity"
      expr: AVG(CAST(yield_quantity AS DOUBLE))
      comment: "Average yield quantity per recipe. Operational efficiency KPI for portion standardization and batch production planning."
    - name: "avg_cook_temperature_f"
      expr: AVG(CAST(cook_temperature_f AS DOUBLE))
      comment: "Average cook temperature in Fahrenheit. Food safety compliance KPI; deviations from HACCP-required temperatures are a critical risk."
    - name: "avg_holding_temperature_f"
      expr: AVG(CAST(holding_temperature_f AS DOUBLE))
      comment: "Average holding temperature in Fahrenheit. Food safety KPI for temperature abuse risk management and HACCP compliance."
    - name: "haccp_ccp_recipe_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN haccp_ccp_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of recipes with a HACCP critical control point. Food safety governance KPI for regulatory audit readiness."
    - name: "gluten_free_recipe_pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_gluten_free = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of recipes certified gluten-free. Menu inclusivity KPI for dietary accommodation portfolio strategy."
    - name: "vegan_recipe_pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_vegan = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of recipes that are vegan. Plant-based portfolio KPI for menu diversification and sustainability strategy."
    - name: "implied_gross_margin_pct"
      expr: ROUND(100.0 * (AVG(CAST(menu_price AS DOUBLE)) - AVG(CAST(food_cost AS DOUBLE))) / NULLIF(AVG(CAST(menu_price AS DOUBLE)), 0), 2)
      comment: "Implied gross margin percentage computed from average menu price minus average food cost. Composite profitability KPI for recipe portfolio management."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_combo_meal`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Combo meal portfolio metrics tracking bundle pricing, discount depth, food cost, and availability across channels, dayparts, and restaurant formats. Supports combo strategy, bundle pricing optimization, and promotional planning decisions."
  source: "`restaurants_ecm`.`menu`.`combo_meal`"
  dimensions:
    - name: "launch_date"
      expr: launch_date
      comment: "Combo meal launch date for pipeline and lifecycle analysis."
    - name: "effective_start_date"
      expr: effective_start_date
      comment: "Start date of the combo meal's active pricing window."
    - name: "combo_type"
      expr: combo_type
      comment: "Type of combo (e.g., value, premium, kids) for portfolio segmentation and pricing strategy analysis."
    - name: "combo_status"
      expr: combo_status
      comment: "Lifecycle status of the combo meal (e.g., active, discontinued, test) for portfolio governance."
    - name: "daypart"
      expr: daypart
      comment: "Target daypart for the combo for daypart-level bundle performance analysis."
    - name: "restaurant_format"
      expr: restaurant_format
      comment: "Restaurant format for format-level combo performance benchmarking."
    - name: "menu_engineering_class"
      expr: menu_engineering_class
      comment: "Menu engineering classification for combo profitability tier analysis."
    - name: "is_national_launch"
      expr: is_national_launch
      comment: "Flag for national vs. regional combo launches for scale and investment analysis."
    - name: "is_customizable"
      expr: is_customizable
      comment: "Flag for customizable combos for operational complexity and upsell opportunity analysis."
    - name: "country_code"
      expr: country_code
      comment: "Country for international combo portfolio management."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of combo pricing amounts for multi-currency normalization."
  measures:
    - name: "total_combo_count"
      expr: COUNT(1)
      comment: "Total number of combo meal records. Tracks combo portfolio size and complexity."
    - name: "avg_bundle_price"
      expr: AVG(CAST(bundle_price AS DOUBLE))
      comment: "Average combo bundle price. Core pricing KPI for combo value positioning and competitive benchmarking."
    - name: "avg_individual_items_price_sum"
      expr: AVG(CAST(individual_items_price_sum AS DOUBLE))
      comment: "Average sum of individual item prices if purchased separately. Used to compute bundle savings and value proposition."
    - name: "avg_bundle_discount_amount"
      expr: AVG(CAST(bundle_discount_amount AS DOUBLE))
      comment: "Average discount provided by purchasing the combo vs. individual items. Measures bundle value proposition and promotional investment."
    - name: "avg_food_cost_pct"
      expr: AVG(CAST(food_cost_pct AS DOUBLE))
      comment: "Average food cost percentage for combo meals. Ensures combo pricing maintains acceptable margin thresholds."
    - name: "avg_item_cost"
      expr: AVG(CAST(item_cost AS DOUBLE))
      comment: "Average total item cost for combo meals. Used to validate combo pricing against cost structure."
    - name: "avg_pmix_target_pct"
      expr: AVG(CAST(pmix_target_pct AS DOUBLE))
      comment: "Average product mix target percentage for combo meals. Informs marketing investment and operational focus for combo promotion."
    - name: "bundle_discount_rate"
      expr: ROUND(100.0 * AVG(CAST(bundle_discount_amount AS DOUBLE)) / NULLIF(AVG(CAST(individual_items_price_sum AS DOUBLE)), 0), 2)
      comment: "Average bundle discount as a percentage of individual item price sum. Measures combo value depth and its impact on revenue per transaction."
    - name: "implied_combo_margin_pct"
      expr: ROUND(100.0 * (AVG(CAST(bundle_price AS DOUBLE)) - AVG(CAST(item_cost AS DOUBLE))) / NULLIF(AVG(CAST(bundle_price AS DOUBLE)), 0), 2)
      comment: "Implied gross margin percentage for combo meals. Composite profitability KPI for combo portfolio management and pricing strategy."
    - name: "digital_channel_availability_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_olo_available = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of combo meals available on OLO (online ordering). Digital channel coverage KPI for e-commerce revenue optimization."
    - name: "third_party_delivery_availability_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_3pd_available = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of combo meals available on third-party delivery platforms. Delivery channel coverage KPI for off-premise revenue strategy."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`menu_nutrition_profile`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Nutritional profile metrics tracking caloric content, macronutrient composition, sodium levels, and regulatory approval status across the menu item portfolio. Supports health and wellness strategy, regulatory compliance, and menu labeling decisions."
  source: "`restaurants_ecm`.`menu`.`nutrition_profile`"
  dimensions:
    - name: "effective_date"
      expr: effective_date
      comment: "Date the nutrition profile became effective for point-in-time nutritional analysis."
    - name: "profile_type"
      expr: profile_type
      comment: "Type of nutrition profile (e.g., standard, as-served, as-prepared) for methodology-level analysis."
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of the nutrition profile for regulatory compliance tracking."
    - name: "data_source"
      expr: data_source
      comment: "Source of nutritional data (e.g., lab analysis, database, supplier) for data quality and credibility assessment."
    - name: "is_current_version"
      expr: is_current_version
      comment: "Flag for the current active version of the nutrition profile for filtering to live menu nutritional data."
  measures:
    - name: "avg_calories"
      expr: AVG(CAST(calories AS DOUBLE))
      comment: "Average calorie count per menu item nutrition profile. Core health KPI for menu wellness strategy and regulatory menu board labeling compliance."
    - name: "avg_total_fat_g"
      expr: AVG(CAST(total_fat_g AS DOUBLE))
      comment: "Average total fat content in grams. Nutritional health KPI for dietary guideline compliance and guest health transparency."
    - name: "avg_saturated_fat_g"
      expr: AVG(CAST(saturated_fat_g AS DOUBLE))
      comment: "Average saturated fat content in grams. Cardiovascular health KPI; high saturated fat levels attract regulatory and public health scrutiny."
    - name: "avg_trans_fat_g"
      expr: AVG(CAST(trans_fat_g AS DOUBLE))
      comment: "Average trans fat content in grams. Regulatory compliance KPI; trans fat limits are mandated in many jurisdictions and require active monitoring."
    - name: "avg_sodium_mg"
      expr: AVG(CAST(sodium_mg AS DOUBLE))
      comment: "Average sodium content in milligrams. High-priority health and regulatory KPI; sodium reduction targets are a key public health commitment for foodservice operators."
    - name: "avg_total_carbohydrate_g"
      expr: AVG(CAST(total_carbohydrate_g AS DOUBLE))
      comment: "Average total carbohydrate content in grams. Nutritional transparency KPI for diabetic and low-carb dietary accommodation."
    - name: "avg_protein_g"
      expr: AVG(CAST(protein_g AS DOUBLE))
      comment: "Average protein content in grams. Nutritional value KPI for high-protein menu positioning and athletic/health-conscious guest segments."
    - name: "avg_added_sugars_g"
      expr: AVG(CAST(added_sugars_g AS DOUBLE))
      comment: "Average added sugars in grams. Regulatory and health KPI; added sugar disclosure is mandated under FDA nutrition labeling rules."
    - name: "avg_serving_size_g"
      expr: AVG(CAST(serving_size_g AS DOUBLE))
      comment: "Average serving size in grams. Portion standardization KPI for consistency in nutritional disclosure and guest value perception."
    - name: "distinct_items_with_nutrition"
      expr: COUNT(DISTINCT menu_item_id)
      comment: "Count of distinct menu items with nutrition profiles. Measures nutritional disclosure coverage across the menu portfolio — gaps expose regulatory non-compliance risk."
    - name: "approved_nutrition_profile_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN approval_status = 'approved' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of nutrition profiles with approved status. Regulatory compliance KPI; unapproved profiles on active menu items create labeling violation risk."
    - name: "high_sodium_item_pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN sodium_mg > 1500 THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of nutrition profiles with sodium content exceeding 1500mg (FDA high-sodium threshold). Public health and regulatory risk KPI for sodium reduction strategy."
$$;