-- Metric views for domain: loyalty | Business: Restaurants | Version: 1 | Generated on: 2026-05-06 03:57:03

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_member`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Strategic member health and engagement metrics derived from the loyalty member master. Tracks active membership base, tier distribution, points economics, and opt-in reach — core KPIs for loyalty program ROI and CRM investment decisions."
  source: "`restaurants_ecm`.`loyalty`.`member`"
  dimensions:
    - name: "program_status"
      expr: program_status
      comment: "Current status of the member's loyalty program enrollment (e.g. Active, Suspended, Churned). Used to segment active vs. lapsed member populations."
    - name: "enrollment_channel"
      expr: enrollment_channel
      comment: "Channel through which the member originally enrolled (e.g. App, Web, In-Store, Drive-Thru). Critical for understanding acquisition channel effectiveness."
    - name: "enrollment_date_month"
      expr: DATE_TRUNC('MONTH', enrollment_date)
      comment: "Month of member enrollment, used for cohort analysis and enrollment trend reporting."
    - name: "last_activity_date_month"
      expr: DATE_TRUNC('MONTH', last_activity_date)
      comment: "Month of the member's most recent loyalty activity, used to identify recency cohorts and churn risk windows."
    - name: "birthday_month"
      expr: birthday_month
      comment: "Member's birth month, used for birthday reward campaign targeting and seasonal engagement analysis."
    - name: "preferred_language"
      expr: preferred_language
      comment: "Member's preferred communication language, used for localization and inclusive marketing segmentation."
    - name: "email_opt_in"
      expr: email_opt_in
      comment: "Whether the member has opted into email marketing communications. Drives reachable audience sizing for email campaigns."
    - name: "push_notification_opt_in"
      expr: push_notification_opt_in
      comment: "Whether the member has opted into push notifications. Drives reachable audience sizing for mobile push campaigns."
    - name: "sms_opt_in"
      expr: sms_opt_in
      comment: "Whether the member has opted into SMS marketing. Drives reachable audience sizing for SMS campaigns."
    - name: "tier_effective_date_month"
      expr: DATE_TRUNC('MONTH', tier_effective_date)
      comment: "Month the member's current tier became effective, used to track tier upgrade/downgrade velocity over time."
  measures:
    - name: "total_active_members"
      expr: COUNT(CASE WHEN program_status = 'Active' THEN member_id END)
      comment: "Count of members with Active program status. The primary KPI for loyalty program scale and health — directly informs investment in program infrastructure and marketing spend."
    - name: "total_enrolled_members"
      expr: COUNT(DISTINCT member_id)
      comment: "Total distinct enrolled members across all statuses. Measures the full reach of the loyalty program and is used to benchmark enrollment growth targets."
    - name: "total_lifetime_points_earned"
      expr: SUM(CAST(lifetime_points_earned AS DOUBLE))
      comment: "Sum of all lifetime points earned across the member base. Reflects total engagement value generated by the program and is a proxy for cumulative transaction volume driven by loyalty."
    - name: "total_lifetime_points_redeemed"
      expr: SUM(CAST(lifetime_points_redeemed AS DOUBLE))
      comment: "Sum of all lifetime points redeemed across the member base. Measures the actual value delivered back to members and the liability drawn down from the points bank."
    - name: "avg_current_points_balance"
      expr: AVG(CAST(current_points_balance AS DOUBLE))
      comment: "Average current points balance per member. Indicates the average unredeemed liability per member and signals whether members are accumulating but not redeeming (engagement gap)."
    - name: "total_current_points_balance"
      expr: SUM(CAST(current_points_balance AS DOUBLE))
      comment: "Total outstanding points balance across all members. Represents the aggregate unredeemed loyalty liability on the balance sheet — a critical finance and risk metric."
    - name: "points_redemption_rate"
      expr: ROUND(100.0 * SUM(CAST(lifetime_points_redeemed AS DOUBLE)) / NULLIF(SUM(CAST(lifetime_points_earned AS DOUBLE)), 0), 2)
      comment: "Percentage of lifetime earned points that have been redeemed. A high rate signals strong program engagement; a low rate may indicate redemption friction or liability accumulation risk."
    - name: "total_points_expiring_soon"
      expr: SUM(CAST(points_expiring_soon AS DOUBLE))
      comment: "Total points across all members that are approaching expiration. Used by marketing to trigger re-engagement campaigns before points expire, protecting member satisfaction and reducing liability write-offs."
    - name: "email_opt_in_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN email_opt_in = TRUE THEN member_id END) / NULLIF(COUNT(DISTINCT member_id), 0), 2)
      comment: "Percentage of enrolled members who have opted into email marketing. Directly determines the reachable email audience size and informs CRM channel investment decisions."
    - name: "push_notification_opt_in_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN push_notification_opt_in = TRUE THEN member_id END) / NULLIF(COUNT(DISTINCT member_id), 0), 2)
      comment: "Percentage of enrolled members opted into push notifications. Determines mobile push reachability and informs app engagement investment."
    - name: "sms_opt_in_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN sms_opt_in = TRUE THEN member_id END) / NULLIF(COUNT(DISTINCT member_id), 0), 2)
      comment: "Percentage of enrolled members opted into SMS communications. Determines SMS campaign reachability and informs channel mix decisions."
    - name: "avg_lifetime_points_earned_per_member"
      expr: AVG(CAST(lifetime_points_earned AS DOUBLE))
      comment: "Average lifetime points earned per member. Measures the depth of engagement per member and is used to benchmark program generosity and member value across cohorts."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_enrollment_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Enrollment funnel and acquisition quality metrics. Tracks enrollment volume, channel mix, verification completion, fraud risk, and welcome offer issuance — KPIs that directly inform acquisition strategy and program onboarding effectiveness."
  source: "`restaurants_ecm`.`loyalty`.`enrollment_event`"
  dimensions:
    - name: "enrollment_channel"
      expr: enrollment_channel
      comment: "Channel through which the enrollment occurred (e.g. App, Web, In-Store). Used to attribute enrollment volume and quality to acquisition channels."
    - name: "enrollment_type"
      expr: enrollment_type
      comment: "Type of enrollment event (e.g. New, Re-enrollment, Referral). Distinguishes organic growth from win-back and referral-driven acquisition."
    - name: "enrollment_status"
      expr: enrollment_status
      comment: "Current status of the enrollment event (e.g. Completed, Pending, Rejected). Used to measure enrollment funnel completion rates."
    - name: "enrollment_country_code"
      expr: enrollment_country_code
      comment: "Country in which the enrollment occurred. Enables geographic segmentation of enrollment volume and quality for international program management."
    - name: "enrollment_device_type"
      expr: enrollment_device_type
      comment: "Device type used during enrollment (e.g. iOS, Android, Desktop). Informs UX investment priorities for the enrollment flow."
    - name: "enrollment_timestamp_month"
      expr: DATE_TRUNC('MONTH', enrollment_timestamp)
      comment: "Month of enrollment, used for trend analysis and cohort construction."
    - name: "fraud_check_status"
      expr: fraud_check_status
      comment: "Result of the fraud check performed at enrollment (e.g. Passed, Flagged, Blocked). Used to monitor enrollment fraud rates and adjust risk thresholds."
    - name: "referral_source"
      expr: referral_source
      comment: "Source of the referral that drove the enrollment. Used to measure referral program effectiveness and attribute member acquisition to referral campaigns."
  measures:
    - name: "total_enrollments"
      expr: COUNT(DISTINCT enrollment_event_id)
      comment: "Total number of enrollment events. The primary volume KPI for loyalty program acquisition — used to track growth against enrollment targets."
    - name: "verified_enrollment_count"
      expr: COUNT(CASE WHEN verification_completed_flag = TRUE THEN enrollment_event_id END)
      comment: "Count of enrollments where identity verification was successfully completed. Measures the quality of the enrolled member base and compliance with KYC requirements."
    - name: "verification_completion_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN verification_completed_flag = TRUE THEN enrollment_event_id END) / NULLIF(COUNT(CASE WHEN verification_required_flag = TRUE THEN enrollment_event_id END), 0), 2)
      comment: "Percentage of enrollments requiring verification that successfully completed it. A low rate signals friction in the verification flow, leading to incomplete member profiles and compliance risk."
    - name: "welcome_offer_issuance_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN welcome_offer_issued_flag = TRUE THEN enrollment_event_id END) / NULLIF(COUNT(DISTINCT enrollment_event_id), 0), 2)
      comment: "Percentage of enrollments where a welcome offer was issued. Measures the reach of the welcome offer program, which is a key driver of first-purchase conversion among new members."
    - name: "email_opt_in_at_enrollment_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN email_opt_in_flag = TRUE THEN enrollment_event_id END) / NULLIF(COUNT(DISTINCT enrollment_event_id), 0), 2)
      comment: "Percentage of new enrollees who opted into email at the point of enrollment. A leading indicator of future email reachability and CRM list quality."
    - name: "marketing_opt_in_at_enrollment_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN marketing_opt_in_flag = TRUE THEN enrollment_event_id END) / NULLIF(COUNT(DISTINCT enrollment_event_id), 0), 2)
      comment: "Percentage of new enrollees who opted into marketing communications at enrollment. Directly determines the addressable marketing audience from new member cohorts."
    - name: "avg_fraud_score_at_enrollment"
      expr: AVG(CAST(fraud_score AS DOUBLE))
      comment: "Average fraud risk score assigned at enrollment. Tracks the overall fraud risk profile of the enrollment pipeline — a rising average signals increased fraud attack pressure requiring intervention."
    - name: "flagged_enrollment_count"
      expr: COUNT(CASE WHEN fraud_check_status = 'Flagged' THEN enrollment_event_id END)
      comment: "Count of enrollments flagged by the fraud check system. Used to monitor fraud attack volume and calibrate fraud detection thresholds."
    - name: "referral_enrollment_count"
      expr: COUNT(CASE WHEN referral_source IS NOT NULL AND referral_source <> '' THEN enrollment_event_id END)
      comment: "Count of enrollments attributed to a referral source. Measures the volume contribution of the referral program to overall member acquisition."
    - name: "terms_acceptance_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN terms_accepted_flag = TRUE THEN enrollment_event_id END) / NULLIF(COUNT(DISTINCT enrollment_event_id), 0), 2)
      comment: "Percentage of enrollments where terms and conditions were accepted. A compliance KPI — any rate below 100% on completed enrollments signals a legal and regulatory risk."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_points_ledger`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Points economics and ledger activity metrics. Tracks points earn rates, transaction volumes, voided activity, and order value associated with points transactions — the financial engine of the loyalty program."
  source: "`restaurants_ecm`.`loyalty`.`points_ledger`"
  dimensions:
    - name: "transaction_type"
      expr: transaction_type
      comment: "Type of points ledger transaction (e.g. Earn, Redeem, Adjust, Expire, Reverse). Used to decompose points movement by type for financial reconciliation."
    - name: "transaction_timestamp_month"
      expr: DATE_TRUNC('MONTH', transaction_timestamp)
      comment: "Month of the points transaction, used for trend analysis and monthly points economics reporting."
    - name: "fiscal_year"
      expr: fiscal_year
      comment: "Fiscal year of the points transaction. Used for annual financial reporting and loyalty program P&L attribution."
    - name: "fiscal_period"
      expr: fiscal_period
      comment: "Fiscal period of the points transaction. Used for period-over-period financial reporting of points liability and earn activity."
    - name: "source_system_code"
      expr: source_system_code
      comment: "Source system that originated the points transaction (e.g. POS, App, OLO). Used to audit data quality and reconcile points across systems."
    - name: "order_currency_code"
      expr: order_currency_code
      comment: "Currency of the originating order. Used for multi-currency points economics analysis in international markets."
    - name: "adjustment_reason_code"
      expr: adjustment_reason_code
      comment: "Reason code for manual points adjustments. Used to categorize and monitor the volume and value of manual interventions in the points ledger."
    - name: "is_voided"
      expr: is_voided
      comment: "Whether the points transaction has been voided. Used to filter clean vs. voided transactions and monitor void rates."
    - name: "points_expiry_date_month"
      expr: DATE_TRUNC('MONTH', points_expiry_date)
      comment: "Month in which the points in this ledger entry are scheduled to expire. Used for forward-looking liability expiration forecasting."
  measures:
    - name: "total_points_transactions"
      expr: COUNT(DISTINCT points_ledger_id)
      comment: "Total number of points ledger transactions. Measures the overall activity volume of the loyalty program and is used to track engagement throughput."
    - name: "total_order_amount"
      expr: SUM(CAST(order_total_amount AS DOUBLE))
      comment: "Total order value associated with points-earning transactions. Measures the revenue base that the loyalty program is driving — a direct linkage between loyalty engagement and top-line sales."
    - name: "avg_order_amount_per_transaction"
      expr: AVG(CAST(order_total_amount AS DOUBLE))
      comment: "Average order value per points-earning transaction. Tracks whether loyalty members are spending more per visit over time — a key measure of program-driven basket size lift."
    - name: "avg_points_earn_rate"
      expr: AVG(CAST(points_earn_rate AS DOUBLE))
      comment: "Average points earn rate applied across transactions. Used to monitor the effective generosity of the program and detect anomalies from rule misconfiguration."
    - name: "voided_transaction_count"
      expr: COUNT(CASE WHEN is_voided = TRUE THEN points_ledger_id END)
      comment: "Count of voided points ledger transactions. A high void rate signals operational issues at POS, fraud, or system integration failures requiring investigation."
    - name: "void_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_voided = TRUE THEN points_ledger_id END) / NULLIF(COUNT(DISTINCT points_ledger_id), 0), 2)
      comment: "Percentage of points transactions that were voided. A rising void rate is an operational and fraud risk signal that triggers investigation and system audits."
    - name: "total_order_amount_on_earn_transactions"
      expr: SUM(CASE WHEN transaction_type = 'Earn' THEN CAST(order_total_amount AS DOUBLE) ELSE 0 END)
      comment: "Total order value on earn-type transactions only. Isolates the revenue base directly attributable to points-earning behavior, used for loyalty-driven revenue attribution."
    - name: "unique_members_with_transactions"
      expr: COUNT(DISTINCT loyalty_member_id)
      comment: "Count of distinct members with at least one points ledger entry in the period. Measures the active transacting member base — a key denominator for per-member economics."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_offer_redemption`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Offer redemption performance and discount economics metrics. Tracks redemption volume, discount value delivered, order lift, and fraud — KPIs that directly inform offer ROI, promotional spend efficiency, and member engagement quality."
  source: "`restaurants_ecm`.`loyalty`.`redemption`"
  dimensions:
    - name: "redemption_status"
      expr: redemption_status
      comment: "Status of the offer redemption (e.g. Completed, Voided, Pending). Used to filter valid redemptions and monitor void/failure rates."
    - name: "member_tier"
      expr: member_tier
      comment: "Loyalty tier of the member at the time of redemption. Used to analyze offer redemption behavior and discount economics by tier segment."
    - name: "daypart"
      expr: daypart
      comment: "Daypart during which the redemption occurred (e.g. Breakfast, Lunch, Dinner). Used to identify peak redemption windows and optimize offer timing."
    - name: "redemption_timestamp_month"
      expr: DATE_TRUNC('MONTH', redemption_timestamp)
      comment: "Month of the offer redemption, used for trend analysis and monthly promotional spend reporting."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the redemption transaction. Used for multi-currency promotional spend analysis in international markets."
  measures:
    - name: "total_discount_amount"
      expr: SUM(CAST(discount_amount AS DOUBLE))
      comment: "Total monetary discount value delivered through offer redemptions. Represents the direct promotional spend — a critical P&L line item for marketing budget management."
    - name: "avg_discount_amount_per_redemption"
      expr: AVG(CAST(discount_amount AS DOUBLE))
      comment: "Average discount value per redemption event. Used to benchmark offer generosity and detect outlier offers that are over-discounting relative to program targets."
    - name: "unique_members_redeeming"
      expr: COUNT(DISTINCT member_id)
      comment: "Count of distinct members who redeemed at least one offer in the period. Measures the breadth of offer engagement across the member base — a key indicator of program activation."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_redemption`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Points redemption economics and reward utilization metrics. Tracks points depletion, discount value delivered, fraud exposure, and order impact from reward redemptions — KPIs for managing loyalty liability and member value delivery."
  source: "`restaurants_ecm`.`loyalty`.`redemption`"
  dimensions:
    - name: "redemption_status"
      expr: redemption_status
      comment: "Status of the redemption (e.g. Completed, Reversed, Voided). Used to isolate valid redemptions and monitor reversal and void rates."
    - name: "reward_type"
      expr: reward_type
      comment: "Type of reward redeemed (e.g. Free Item, Discount, Experience). Used to analyze redemption mix and reward portfolio performance."
    - name: "member_tier"
      expr: member_tier
      comment: "Loyalty tier of the member at the time of redemption. Used to analyze redemption behavior and discount economics by tier segment."
    - name: "daypart"
      expr: daypart
      comment: "Daypart during which the redemption occurred. Used to identify peak redemption windows and optimize reward availability."
    - name: "redemption_source"
      expr: redemption_source
      comment: "Source system or channel that originated the redemption (e.g. App, POS, OLO). Used to attribute redemption volume to channels and audit cross-channel consistency."
    - name: "redemption_timestamp_month"
      expr: DATE_TRUNC('MONTH', redemption_timestamp)
      comment: "Month of the redemption event, used for trend analysis and monthly liability drawdown reporting."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the redemption transaction. Used for multi-currency redemption economics analysis."
    - name: "fraud_flag"
      expr: fraud_flag
      comment: "Whether the redemption was flagged as potentially fraudulent. Used to monitor fraud exposure in the redemption pipeline."
    - name: "third_party_delivery_partner"
      expr: third_party_delivery_partner
      comment: "Third-party delivery partner associated with the redemption (e.g. DoorDash, Uber Eats). Used to analyze redemption behavior and discount economics on third-party channels."
  measures:
    - name: "total_redemptions"
      expr: COUNT(DISTINCT redemption_id)
      comment: "Total number of reward redemptions. The primary volume KPI for reward utilization — used to track redemption against program targets and measure member engagement depth."
    - name: "total_discount_amount"
      expr: SUM(CAST(discount_amount AS DOUBLE))
      comment: "Total monetary discount value delivered through reward redemptions. Represents the direct cost of rewards redeemed — a critical loyalty program P&L line item."
    - name: "avg_discount_per_redemption"
      expr: AVG(CAST(discount_amount AS DOUBLE))
      comment: "Average discount value per redemption. Used to benchmark reward generosity and detect outlier reward types that are over-delivering discount relative to program economics."
    - name: "total_order_value_before_discount"
      expr: SUM(CAST(order_total_before_discount AS DOUBLE))
      comment: "Total pre-discount order value on redemption transactions. Measures the revenue base that reward redemptions are attached to — used for loyalty-driven revenue attribution."
    - name: "total_order_value_after_discount"
      expr: SUM(CAST(order_total_after_discount AS DOUBLE))
      comment: "Total post-discount order value on redemption transactions. Measures net revenue realized after reward discounts are applied."
    - name: "discount_to_order_ratio"
      expr: ROUND(100.0 * SUM(CAST(discount_amount AS DOUBLE)) / NULLIF(SUM(CAST(order_total_before_discount AS DOUBLE)), 0), 2)
      comment: "Total discount amount as a percentage of total pre-discount order value. Measures the effective discount depth of the rewards program — a key margin management KPI."
    - name: "avg_fraud_score"
      expr: AVG(CAST(fraud_score AS DOUBLE))
      comment: "Average fraud risk score across redemption events. Tracks the overall fraud risk profile of the redemption pipeline — a rising average signals increased fraud pressure requiring security intervention."
    - name: "fraudulent_redemption_count"
      expr: COUNT(CASE WHEN fraud_flag = TRUE THEN redemption_id END)
      comment: "Count of redemptions flagged as fraudulent. Measures the absolute fraud exposure in the redemption pipeline — directly informs fraud prevention investment and policy decisions."
    - name: "fraud_redemption_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN fraud_flag = TRUE THEN redemption_id END) / NULLIF(COUNT(DISTINCT redemption_id), 0), 2)
      comment: "Percentage of redemptions flagged as fraudulent. A rising rate is a critical risk signal that triggers security audits, rule tightening, and potential program suspension decisions."
    - name: "unique_members_redeeming"
      expr: COUNT(DISTINCT member_id)
      comment: "Count of distinct members who completed at least one reward redemption in the period. Measures the breadth of reward utilization across the member base."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_offer_assignment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Offer distribution and engagement funnel metrics. Tracks offer delivery, open, click, and redemption rates from assignment through conversion — KPIs for measuring offer campaign effectiveness and personalization ROI."
  source: "`restaurants_ecm`.`loyalty`.`offer_assignment`"
  dimensions:
    - name: "assignment_channel"
      expr: assignment_channel
      comment: "Channel through which the offer was assigned to the member (e.g. App, Email, Push, SMS). Used to attribute offer engagement metrics to distribution channels."
    - name: "assignment_type"
      expr: assignment_type
      comment: "Type of offer assignment (e.g. Targeted, Broadcast, Triggered). Used to compare engagement rates across assignment strategies."
    - name: "delivery_status"
      expr: delivery_status
      comment: "Status of the offer delivery to the member (e.g. Delivered, Failed, Pending). Used to monitor delivery success rates and identify channel delivery failures."
    - name: "redemption_status"
      expr: redemption_status
      comment: "Current redemption status of the assigned offer (e.g. Redeemed, Unredeemed, Expired). Used to measure conversion from assignment to redemption."
    - name: "ab_test_variant"
      expr: ab_test_variant
      comment: "A/B test variant assigned to this offer assignment. Used to compare engagement and redemption rates across test variants to optimize offer design."
    - name: "assignment_timestamp_month"
      expr: DATE_TRUNC('MONTH', assignment_timestamp)
      comment: "Month of offer assignment, used for trend analysis and monthly campaign performance reporting."
    - name: "is_wallet_visible"
      expr: is_wallet_visible
      comment: "Whether the offer is visible in the member's digital wallet. Used to analyze the impact of wallet visibility on redemption rates."
  measures:
    - name: "total_offer_assignments"
      expr: COUNT(DISTINCT offer_assignment_id)
      comment: "Total number of offer assignments issued to members. The primary distribution volume KPI — used to track offer campaign reach against targeting goals."
    - name: "delivered_assignment_count"
      expr: COUNT(CASE WHEN delivery_status = 'Delivered' THEN offer_assignment_id END)
      comment: "Count of offer assignments successfully delivered to members. Measures the effective reach of the offer campaign after accounting for delivery failures."
    - name: "delivery_success_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN delivery_status = 'Delivered' THEN offer_assignment_id END) / NULLIF(COUNT(DISTINCT offer_assignment_id), 0), 2)
      comment: "Percentage of offer assignments that were successfully delivered. A low rate signals channel delivery failures (e.g. push notification opt-out, email bounces) requiring channel health investigation."
    - name: "offer_open_count"
      expr: COUNT(CASE WHEN opened_timestamp IS NOT NULL THEN offer_assignment_id END)
      comment: "Count of offer assignments that were opened by the member. Measures top-of-funnel engagement with distributed offers."
    - name: "offer_open_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN opened_timestamp IS NOT NULL THEN offer_assignment_id END) / NULLIF(COUNT(CASE WHEN delivery_status = 'Delivered' THEN offer_assignment_id END), 0), 2)
      comment: "Percentage of delivered offers that were opened by the member. A key engagement funnel metric — low open rates signal poor offer relevance or notification fatigue."
    - name: "offer_click_count"
      expr: COUNT(CASE WHEN clicked_timestamp IS NOT NULL THEN offer_assignment_id END)
      comment: "Count of offer assignments where the member clicked through to the offer detail. Measures mid-funnel engagement and intent to redeem."
    - name: "offer_click_through_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN clicked_timestamp IS NOT NULL THEN offer_assignment_id END) / NULLIF(COUNT(CASE WHEN opened_timestamp IS NOT NULL THEN offer_assignment_id END), 0), 2)
      comment: "Percentage of opened offers that were clicked through. Measures the quality of offer creative and relevance in driving member intent — a key personalization effectiveness KPI."
    - name: "offer_redemption_conversion_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN redemption_status = 'Redeemed' THEN offer_assignment_id END) / NULLIF(COUNT(DISTINCT offer_assignment_id), 0), 2)
      comment: "Percentage of assigned offers that were ultimately redeemed. The end-to-end offer conversion rate — the primary ROI KPI for offer campaigns, directly informing future campaign investment decisions."
    - name: "avg_personalization_score"
      expr: AVG(CAST(personalization_score AS DOUBLE))
      comment: "Average personalization relevance score assigned to offer-member pairings. Tracks the quality of the personalization engine — higher scores should correlate with higher redemption rates."
    - name: "unique_members_assigned"
      expr: COUNT(DISTINCT loyalty_member_id)
      comment: "Count of distinct members who received at least one offer assignment in the period. Measures the breadth of offer campaign reach across the member base."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_tier_history`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Tier movement and qualification metrics. Tracks upgrade and downgrade velocity, manual override rates, qualification economics, and notification effectiveness — KPIs for managing tier program health and member progression."
  source: "`restaurants_ecm`.`loyalty`.`tier_history`"
  dimensions:
    - name: "tier_change_type"
      expr: tier_change_type
      comment: "Type of tier change event (e.g. Upgrade, Downgrade, Renewal, Expiry). Used to decompose tier movement volume by direction and type."
    - name: "tier_change_reason_code"
      expr: tier_change_reason_code
      comment: "Reason code for the tier change. Used to categorize the drivers of tier movement (e.g. Qualification, Promotion, Manual Override, Expiry)."
    - name: "previous_tier_code"
      expr: previous_tier_code
      comment: "Code of the tier the member was in before the change. Used to analyze tier transition flows and identify which tiers have the highest churn or upgrade rates."
    - name: "processing_channel"
      expr: processing_channel
      comment: "Channel through which the tier change was processed (e.g. Batch, Real-Time, Manual). Used to monitor processing channel mix and identify latency issues."
    - name: "notification_channel"
      expr: notification_channel
      comment: "Channel used to notify the member of their tier change (e.g. Email, Push, SMS). Used to analyze notification delivery effectiveness by channel."
    - name: "tier_change_timestamp_month"
      expr: DATE_TRUNC('MONTH', tier_change_timestamp)
      comment: "Month of the tier change event, used for trend analysis and monthly tier movement reporting."
    - name: "is_manual_override"
      expr: is_manual_override
      comment: "Whether the tier change was a manual override by an employee. Used to monitor the rate of manual interventions in the tier qualification process."
    - name: "is_promotional_tier"
      expr: is_promotional_tier
      comment: "Whether the tier change was driven by a promotional campaign rather than standard qualification. Used to separate organic tier progression from promotional tier grants."
  measures:
    - name: "total_tier_changes"
      expr: COUNT(DISTINCT tier_history_id)
      comment: "Total number of tier change events. Measures the overall velocity of tier movement in the program — high velocity may indicate tier threshold miscalibration or aggressive promotional tier grants."
    - name: "tier_upgrade_count"
      expr: COUNT(CASE WHEN tier_change_type = 'Upgrade' THEN tier_history_id END)
      comment: "Count of tier upgrade events. Measures the rate at which members are progressing to higher tiers — a positive engagement signal and indicator of program aspiration effectiveness."
    - name: "tier_downgrade_count"
      expr: COUNT(CASE WHEN tier_change_type = 'Downgrade' THEN tier_history_id END)
      comment: "Count of tier downgrade events. A rising downgrade count signals member disengagement or overly aggressive qualification thresholds — triggers program design review."
    - name: "upgrade_to_downgrade_ratio"
      expr: ROUND(CAST(COUNT(CASE WHEN tier_change_type = 'Upgrade' THEN tier_history_id END) AS DOUBLE) / NULLIF(COUNT(CASE WHEN tier_change_type = 'Downgrade' THEN tier_history_id END), 0), 2)
      comment: "Ratio of tier upgrades to tier downgrades. A ratio above 1 indicates net positive tier progression across the member base — a key program health indicator for loyalty leadership."
    - name: "manual_override_count"
      expr: COUNT(CASE WHEN is_manual_override = TRUE THEN tier_history_id END)
      comment: "Count of tier changes executed as manual overrides. A high count signals operational inefficiency or policy exceptions that may indicate program rule gaps requiring governance review."
    - name: "manual_override_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_manual_override = TRUE THEN tier_history_id END) / NULLIF(COUNT(DISTINCT tier_history_id), 0), 2)
      comment: "Percentage of tier changes that were manual overrides. A rising rate is a governance and operational risk signal — manual overrides bypass automated qualification rules and create inconsistent member experiences."
    - name: "notification_sent_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN notification_sent_flag = TRUE THEN tier_history_id END) / NULLIF(COUNT(DISTINCT tier_history_id), 0), 2)
      comment: "Percentage of tier changes where a notification was successfully sent to the member. A low rate means members are not being informed of their tier changes — a key driver of tier benefit awareness and engagement."
    - name: "avg_qualifying_points_balance"
      expr: AVG(CAST(qualifying_points_balance AS DOUBLE))
      comment: "Average qualifying points balance at the time of tier change. Used to benchmark the actual qualification level of members changing tiers against the program's stated thresholds."
    - name: "avg_qualifying_spend_amount"
      expr: AVG(CAST(qualifying_spend_amount AS DOUBLE))
      comment: "Average qualifying spend amount at the time of tier change. Measures the average revenue contribution of members at the point of tier qualification — used to calibrate spend-based tier thresholds."
    - name: "total_qualifying_spend_amount"
      expr: SUM(CAST(qualifying_spend_amount AS DOUBLE))
      comment: "Total qualifying spend across all tier change events. Measures the aggregate revenue contribution associated with tier qualification activity — links tier program investment to revenue outcomes."
    - name: "unique_members_with_tier_changes"
      expr: COUNT(DISTINCT loyalty_member_id)
      comment: "Count of distinct members who experienced a tier change in the period. Measures the breadth of tier movement activity across the member base."
$$;

CREATE OR REPLACE VIEW `restaurants_ecm`.`_metrics`.`loyalty_accrual_rule`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Accrual rule portfolio governance metrics. Tracks the configuration, scope, and economics of points earning rules — KPIs for managing program generosity, rule complexity, and tier multiplier coverage."
  source: "`restaurants_ecm`.`loyalty`.`accrual_rule`"
  dimensions:
    - name: "rule_status"
      expr: rule_status
      comment: "Current status of the accrual rule (e.g. Active, Inactive, Pending). Used to monitor the active rule portfolio and identify stale or unapproved rules."
    - name: "rule_type"
      expr: rule_type
      comment: "Type of accrual rule (e.g. Base Earn, Bonus, Multiplier, Category). Used to decompose the rule portfolio by earning mechanism."
    - name: "earning_basis"
      expr: earning_basis
      comment: "Basis on which points are earned (e.g. Dollar Spend, Visit, Item Purchase). Used to analyze the distribution of earning mechanisms across the rule portfolio."
    - name: "channel_scope"
      expr: channel_scope
      comment: "Channel scope of the accrual rule (e.g. App, POS, All Channels). Used to analyze rule coverage across ordering channels."
    - name: "franchise_scope"
      expr: franchise_scope
      comment: "Franchise scope of the accrual rule (e.g. All, Company-Owned, Specific Franchisee). Used to analyze rule applicability across the franchise network."
    - name: "member_tier_scope"
      expr: member_tier_scope
      comment: "Member tier scope of the accrual rule. Used to analyze which tiers are covered by which earning rules and identify tier-specific earning gaps."
    - name: "effective_start_date_month"
      expr: DATE_TRUNC('MONTH', effective_start_date)
      comment: "Month the accrual rule became effective. Used to track rule portfolio evolution over time."
    - name: "stackable"
      expr: stackable
      comment: "Whether the accrual rule can be stacked with other rules. Used to identify rules that contribute to compound earning scenarios and manage liability exposure."
    - name: "tier_multiplier_applicable"
      expr: tier_multiplier_applicable
      comment: "Whether a tier multiplier is applied on top of this rule. Used to analyze the distribution of tier-enhanced earning rules across the portfolio."
  measures:
    - name: "total_active_rules"
      expr: COUNT(CASE WHEN rule_status = 'Active' THEN accrual_rule_id END)
      comment: "Count of currently active accrual rules. Measures the complexity of the active earning rule portfolio — excessive rule counts increase operational risk and member confusion."
    - name: "total_rules"
      expr: COUNT(DISTINCT accrual_rule_id)
      comment: "Total count of accrual rules across all statuses. Used to track rule portfolio size and governance overhead."
    - name: "avg_points_per_unit"
      expr: AVG(CAST(points_per_unit AS DOUBLE))
      comment: "Average points awarded per unit (e.g. per dollar spent) across active rules. Measures the average generosity of the earning rule portfolio — used to benchmark against competitive programs and manage liability."
    - name: "avg_minimum_purchase_amount"
      expr: AVG(CAST(minimum_purchase_amount AS DOUBLE))
      comment: "Average minimum purchase amount required to trigger points earning across rules. Used to assess whether earning thresholds are appropriately calibrated to drive incremental spend."
    - name: "stackable_rule_count"
      expr: COUNT(CASE WHEN stackable = TRUE THEN accrual_rule_id END)
      comment: "Count of accrual rules that are stackable with other rules. A high count increases the risk of unintended compound earning scenarios that can create excessive liability — a key governance KPI."
    - name: "stackable_rule_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN stackable = TRUE THEN accrual_rule_id END) / NULLIF(COUNT(CASE WHEN rule_status = 'Active' THEN accrual_rule_id END), 0), 2)
      comment: "Percentage of active accrual rules that are stackable. Used by program governance teams to monitor compound earning risk exposure across the active rule portfolio."
    - name: "tier_multiplier_rule_count"
      expr: COUNT(CASE WHEN tier_multiplier_applicable = TRUE THEN accrual_rule_id END)
      comment: "Count of accrual rules where a tier multiplier is applicable. Measures the breadth of tier-enhanced earning in the rule portfolio — used to assess the incremental value delivered to higher-tier members."
$$;