-- Metric views for domain: customer | Business: Banking | Version: 1 | Generated on: 2026-05-02 22:51:12

CREATE OR REPLACE VIEW `banking_ecm`.`_metrics`.`customer_complaint`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Key complaint performance metrics for monitoring customer experience and SLA adherence"
  source: "`banking_ecm`.`customer`.`complaint`"
  dimensions:
    - name: "complaint_status"
      expr: complaint_status
      comment: "Current status of the complaint (e.g., Open, Resolved)"
  measures:
    - name: "total_complaints"
      expr: COUNT(1)
      comment: "Total number of customer complaints recorded"
    - name: "total_sla_breaches"
      expr: SUM(CASE WHEN sla_breach_flag THEN 1 ELSE 0 END)
      comment: "Count of complaints that breached the service level agreement"
    - name: "avg_resolution_time_days"
      expr: AVG(DATEDIFF(resolution_timestamp, complaint_timestamp))
      comment: "Average time (in days) to resolve a complaint"
$$;

CREATE OR REPLACE VIEW `banking_ecm`.`_metrics`.`customer_account_holder`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Metrics to assess account holder onboarding and ownership structures"
  source: "`banking_ecm`.`customer`.`account_holder`"
  dimensions:
    - name: "ownership_role"
      expr: ownership_role
      comment: "Role describing the nature of ownership (e.g., Primary, Joint)"
  measures:
    - name: "total_account_holders"
      expr: COUNT(1)
      comment: "Total number of account holder records"
    - name: "avg_ownership_percentage"
      expr: AVG(CAST(ownership_percentage AS DOUBLE))
      comment: "Average ownership percentage across account holders"
    - name: "total_approved_holders"
      expr: SUM(CASE WHEN approved_by_employee_id IS NOT NULL THEN 1 ELSE 0 END)
      comment: "Number of account holders that have been approved by an employee"
$$;

CREATE OR REPLACE VIEW `banking_ecm`.`_metrics`.`customer_kyc_record`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "KYC performance and risk profiling metrics"
  source: "`banking_ecm`.`customer`.`kyc_record`"
  dimensions:
    - name: "kyc_status"
      expr: kyc_status
      comment: "Current status of the KYC process"
  measures:
    - name: "total_kyc_records"
      expr: COUNT(1)
      comment: "Total KYC records processed"
    - name: "avg_overall_risk_score"
      expr: AVG(CAST(overall_risk_score AS DOUBLE))
      comment: "Average overall risk score from KYC assessments"
    - name: "high_risk_kyc_count"
      expr: SUM(CASE WHEN overall_risk_score >= 80 THEN 1 ELSE 0 END)
      comment: "Count of KYC records flagged as high risk (score >= 80)"
$$;

CREATE OR REPLACE VIEW `banking_ecm`.`_metrics`.`customer_marketing_campaign`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Financial and performance metrics for marketing campaigns"
  source: "`banking_ecm`.`customer`.`marketing_campaign`"
  dimensions:
    - name: "campaign_status"
      expr: campaign_status
      comment: "Current lifecycle status of the campaign"
  measures:
    - name: "total_budget_amount"
      expr: SUM(CAST(budget_amount AS DOUBLE))
      comment: "Total budget allocated to marketing campaigns"
    - name: "total_actual_spend"
      expr: SUM(CAST(actual_spend_amount AS DOUBLE))
      comment: "Actual spend incurred by campaigns"
    - name: "total_actual_reach"
      expr: SUM(CAST(actual_reach AS DOUBLE))
      comment: "Total number of individuals reached by campaigns"
    - name: "total_conversions"
      expr: SUM(CAST(conversion_count AS DOUBLE))
      comment: "Total number of conversions generated by campaigns"
$$;

CREATE OR REPLACE VIEW `banking_ecm`.`_metrics`.`customer_risk_rating`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Aggregated risk rating metrics to monitor portfolio risk exposure"
  source: "`banking_ecm`.`customer`.`risk_rating`"
  dimensions:
    - name: "risk_tier_code_list_id"
      expr: risk_tier_code_list_id
      comment: "Risk tier classification code"
  measures:
    - name: "total_risk_records"
      expr: COUNT(1)
      comment: "Total risk rating records for customers"
    - name: "avg_overall_risk_score"
      expr: AVG(CAST(overall_risk_score AS DOUBLE))
      comment: "Average overall risk score across customers"
    - name: "high_risk_count"
      expr: SUM(CASE WHEN overall_risk_score >= 80 THEN 1 ELSE 0 END)
      comment: "Number of customers classified as high risk (score >= 80)"
$$;