-- Metric views for domain: investment | Business: Real Estate | Version: 1 | Generated on: 2026-05-02 01:37:58

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_fund_performance`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Core fund performance metrics including IRR, multiples, NAV, and benchmark comparisons for investment decision-making and investor reporting"
  source: "`real_estate_ecm`.`investment`.`fund_performance`"
  dimensions:
    - name: "performance_period_type"
      expr: period_type
      comment: "Type of performance measurement period (quarterly, annual, inception-to-date)"
    - name: "performance_status"
      expr: period_status
      comment: "Status of the performance period (preliminary, final, audited)"
    - name: "nav_methodology"
      expr: nav_methodology
      comment: "Methodology used for NAV calculation (fair value, cost basis, etc.)"
    - name: "auditor_signoff_status"
      expr: auditor_signoff_status
      comment: "Auditor approval status for the performance period"
    - name: "performance_year"
      expr: YEAR(period_end_date)
      comment: "Calendar year of performance period end"
    - name: "performance_quarter"
      expr: CONCAT('Q', QUARTER(period_end_date), '-', YEAR(period_end_date))
      comment: "Calendar quarter of performance period"
  measures:
    - name: "total_aum"
      expr: SUM(CAST(aum AS DOUBLE))
      comment: "Total assets under management across all funds"
    - name: "total_nav"
      expr: SUM(CAST(nav AS DOUBLE))
      comment: "Total net asset value across all funds"
    - name: "total_gav"
      expr: SUM(CAST(gav AS DOUBLE))
      comment: "Total gross asset value across all funds"
    - name: "avg_net_irr"
      expr: AVG(CAST(net_irr AS DOUBLE))
      comment: "Average net internal rate of return across funds"
    - name: "avg_gross_irr"
      expr: AVG(CAST(gross_irr AS DOUBLE))
      comment: "Average gross internal rate of return across funds"
    - name: "avg_equity_multiple"
      expr: AVG(CAST(equity_multiple AS DOUBLE))
      comment: "Average equity multiple (MOIC) across funds"
    - name: "avg_tvpi"
      expr: AVG(CAST(tvpi AS DOUBLE))
      comment: "Average total value to paid-in capital ratio"
    - name: "avg_dpi"
      expr: AVG(CAST(dpi AS DOUBLE))
      comment: "Average distributions to paid-in capital ratio"
    - name: "avg_rvpi"
      expr: AVG(CAST(rvpi AS DOUBLE))
      comment: "Average residual value to paid-in capital ratio"
    - name: "total_noi"
      expr: SUM(CAST(noi AS DOUBLE))
      comment: "Total net operating income generated by fund portfolios"
    - name: "total_revenue"
      expr: SUM(CAST(total_revenue AS DOUBLE))
      comment: "Total revenue generated by fund portfolios"
    - name: "total_opex"
      expr: SUM(CAST(opex AS DOUBLE))
      comment: "Total operating expenses across fund portfolios"
    - name: "avg_leverage_ratio"
      expr: AVG(CAST(leverage_ratio AS DOUBLE))
      comment: "Average leverage ratio across funds"
    - name: "avg_cap_rate"
      expr: AVG(CAST(cap_rate AS DOUBLE))
      comment: "Average capitalization rate across fund portfolios"
    - name: "total_distributions"
      expr: SUM(CAST(total_distributions AS DOUBLE))
      comment: "Total distributions made to investors"
    - name: "avg_alpha"
      expr: AVG(CAST(alpha AS DOUBLE))
      comment: "Average alpha (excess return vs benchmark) across funds"
    - name: "fund_count"
      expr: COUNT(DISTINCT fund_id)
      comment: "Number of distinct funds in the performance period"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_asset_performance`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Asset-level investment performance metrics including returns, NOI, occupancy, and valuation for portfolio management and asset allocation decisions"
  source: "`real_estate_ecm`.`investment`.`asset_performance`"
  dimensions:
    - name: "performance_period_type"
      expr: period_type
      comment: "Type of performance measurement period (monthly, quarterly, annual)"
    - name: "performance_status"
      expr: performance_status
      comment: "Status of asset performance record (preliminary, final, restated)"
    - name: "hold_period_years"
      expr: hold_period_years
      comment: "Investment hold period in years"
    - name: "sensitivity_scenario"
      expr: sensitivity_scenario
      comment: "Sensitivity analysis scenario (base, upside, downside)"
    - name: "performance_year"
      expr: YEAR(performance_period_end_date)
      comment: "Calendar year of performance period end"
    - name: "performance_quarter"
      expr: CONCAT('Q', QUARTER(performance_period_end_date), '-', YEAR(performance_period_end_date))
      comment: "Calendar quarter of performance period"
  measures:
    - name: "total_noi"
      expr: SUM(CAST(noi AS DOUBLE))
      comment: "Total net operating income across assets"
    - name: "total_pgi"
      expr: SUM(CAST(pgi AS DOUBLE))
      comment: "Total potential gross income across assets"
    - name: "total_egi"
      expr: SUM(CAST(egi AS DOUBLE))
      comment: "Total effective gross income across assets"
    - name: "total_operating_expenses"
      expr: SUM(CAST(operating_expenses AS DOUBLE))
      comment: "Total operating expenses across assets"
    - name: "total_capex"
      expr: SUM(CAST(capex AS DOUBLE))
      comment: "Total capital expenditures across assets"
    - name: "avg_occupancy_rate"
      expr: AVG(CAST(occupancy_rate AS DOUBLE))
      comment: "Average occupancy rate across assets"
    - name: "avg_vacancy_rate"
      expr: AVG(CAST(vacancy_rate AS DOUBLE))
      comment: "Average vacancy rate across assets"
    - name: "avg_cap_rate"
      expr: AVG(CAST(cap_rate AS DOUBLE))
      comment: "Average capitalization rate across assets"
    - name: "avg_exit_cap_rate"
      expr: AVG(CAST(exit_cap_rate AS DOUBLE))
      comment: "Average exit capitalization rate for disposition modeling"
    - name: "avg_levered_irr"
      expr: AVG(CAST(levered_irr AS DOUBLE))
      comment: "Average levered internal rate of return across assets"
    - name: "avg_unlevered_irr"
      expr: AVG(CAST(unlevered_irr AS DOUBLE))
      comment: "Average unlevered internal rate of return across assets"
    - name: "avg_total_return"
      expr: AVG(CAST(total_return AS DOUBLE))
      comment: "Average total return across assets"
    - name: "avg_cash_on_cash_return"
      expr: AVG(CAST(cash_on_cash_return AS DOUBLE))
      comment: "Average cash-on-cash return across assets"
    - name: "avg_dscr"
      expr: AVG(CAST(dscr AS DOUBLE))
      comment: "Average debt service coverage ratio across assets"
    - name: "avg_ltv_ratio"
      expr: AVG(CAST(ltv_ratio AS DOUBLE))
      comment: "Average loan-to-value ratio across assets"
    - name: "total_appraised_value"
      expr: SUM(CAST(appraised_value AS DOUBLE))
      comment: "Total appraised value across assets"
    - name: "total_npv"
      expr: SUM(CAST(npv AS DOUBLE))
      comment: "Total net present value across assets"
    - name: "total_terminal_value"
      expr: SUM(CAST(terminal_value AS DOUBLE))
      comment: "Total terminal value across assets"
    - name: "avg_revenue_psf"
      expr: AVG(CAST(revenue_psf AS DOUBLE))
      comment: "Average revenue per square foot across assets"
    - name: "avg_opex_psf"
      expr: AVG(CAST(opex_psf AS DOUBLE))
      comment: "Average operating expense per square foot across assets"
    - name: "asset_count"
      expr: COUNT(DISTINCT asset_id)
      comment: "Number of distinct assets in performance measurement"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_capital_account`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Investor capital account metrics tracking contributions, distributions, returns, and performance for LP reporting and waterfall calculations"
  source: "`real_estate_ecm`.`investment`.`capital_account`"
  dimensions:
    - name: "fiscal_year"
      expr: fiscal_year
      comment: "Fiscal year of capital account statement"
    - name: "fiscal_quarter"
      expr: fiscal_quarter
      comment: "Fiscal quarter of capital account statement"
    - name: "period_type"
      expr: period_type
      comment: "Type of reporting period (quarterly, annual, inception-to-date)"
    - name: "statement_status"
      expr: statement_status
      comment: "Status of capital account statement (draft, final, audited)"
    - name: "is_tax_exempt_investor"
      expr: is_tax_exempt_investor
      comment: "Whether investor is tax-exempt (impacts distribution treatment)"
  measures:
    - name: "total_capital_contributions"
      expr: SUM(CAST(capital_contributions AS DOUBLE))
      comment: "Total capital contributions from investors in period"
    - name: "total_capital_distributions"
      expr: SUM(CAST(capital_distributions AS DOUBLE))
      comment: "Total capital distributions to investors in period"
    - name: "total_cumulative_contributions"
      expr: SUM(CAST(cumulative_contributions AS DOUBLE))
      comment: "Total cumulative contributions since inception"
    - name: "total_cumulative_distributions"
      expr: SUM(CAST(cumulative_distributions AS DOUBLE))
      comment: "Total cumulative distributions since inception"
    - name: "total_beginning_capital_balance"
      expr: SUM(CAST(beginning_capital_balance AS DOUBLE))
      comment: "Total beginning capital balance for period"
    - name: "total_ending_capital_balance"
      expr: SUM(CAST(ending_capital_balance AS DOUBLE))
      comment: "Total ending capital balance for period"
    - name: "total_allocated_income_loss"
      expr: SUM(CAST(allocated_income_loss AS DOUBLE))
      comment: "Total income or loss allocated to investors in period"
    - name: "total_realized_gain_loss"
      expr: SUM(CAST(realized_gain_loss AS DOUBLE))
      comment: "Total realized gains or losses in period"
    - name: "total_unrealized_gain_loss"
      expr: SUM(CAST(unrealized_gain_loss AS DOUBLE))
      comment: "Total unrealized gains or losses in period"
    - name: "total_carried_interest_allocated"
      expr: SUM(CAST(carried_interest_allocated AS DOUBLE))
      comment: "Total carried interest allocated to GP in period"
    - name: "total_management_fees_charged"
      expr: SUM(CAST(management_fees_charged AS DOUBLE))
      comment: "Total management fees charged in period"
    - name: "total_preferred_return_accrued"
      expr: SUM(CAST(preferred_return_accrued AS DOUBLE))
      comment: "Total preferred return accrued in period"
    - name: "avg_dpi"
      expr: AVG(CAST(dpi AS DOUBLE))
      comment: "Average distributions to paid-in capital ratio"
    - name: "avg_rvpi"
      expr: AVG(CAST(rvpi AS DOUBLE))
      comment: "Average residual value to paid-in capital ratio"
    - name: "avg_moic"
      expr: AVG(CAST(moic AS DOUBLE))
      comment: "Average multiple on invested capital"
    - name: "avg_inception_to_date_irr"
      expr: AVG(CAST(inception_to_date_irr AS DOUBLE))
      comment: "Average inception-to-date internal rate of return"
    - name: "total_commitment_amount"
      expr: SUM(CAST(total_commitment_amount AS DOUBLE))
      comment: "Total investor commitment amounts"
    - name: "total_uncalled_commitment"
      expr: SUM(CAST(uncalled_commitment_amount AS DOUBLE))
      comment: "Total uncalled commitment remaining"
    - name: "investor_count"
      expr: COUNT(DISTINCT investor_id)
      comment: "Number of distinct investors with capital accounts"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_capital_call`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Capital call metrics tracking funding requests, commitments, and investor responsiveness for cash flow management and default monitoring"
  source: "`real_estate_ecm`.`investment`.`capital_call`"
  dimensions:
    - name: "call_status"
      expr: call_status
      comment: "Status of capital call (pending, funded, defaulted, cancelled)"
    - name: "call_type"
      expr: call_type
      comment: "Type of capital call (investment, fees, expenses, recallable)"
    - name: "call_purpose"
      expr: call_purpose
      comment: "Purpose of capital call (acquisition, development, operating, etc.)"
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of capital call"
    - name: "is_default"
      expr: is_default
      comment: "Whether investor defaulted on capital call"
    - name: "is_recallable"
      expr: is_recallable
      comment: "Whether capital call is recallable"
    - name: "call_year"
      expr: YEAR(call_date)
      comment: "Calendar year of capital call"
    - name: "call_quarter"
      expr: CONCAT('Q', QUARTER(call_date), '-', YEAR(call_date))
      comment: "Calendar quarter of capital call"
  measures:
    - name: "total_call_amount"
      expr: SUM(CAST(call_amount AS DOUBLE))
      comment: "Total capital call amount requested"
    - name: "total_funded_amount"
      expr: SUM(CAST(funded_amount AS DOUBLE))
      comment: "Total capital call amount actually funded"
    - name: "total_shortfall_amount"
      expr: SUM(CAST(shortfall_amount AS DOUBLE))
      comment: "Total shortfall between called and funded amounts"
    - name: "total_penalty_amount"
      expr: SUM(CAST(penalty_amount AS DOUBLE))
      comment: "Total penalties assessed for late or defaulted calls"
    - name: "total_cumulative_called"
      expr: SUM(CAST(cumulative_called_amount AS DOUBLE))
      comment: "Total cumulative capital called to date"
    - name: "total_uncalled_commitment"
      expr: SUM(CAST(uncalled_commitment_amount AS DOUBLE))
      comment: "Total uncalled commitment remaining"
    - name: "avg_call_percentage"
      expr: AVG(CAST(call_percentage AS DOUBLE))
      comment: "Average percentage of commitment called"
    - name: "capital_call_count"
      expr: COUNT(1)
      comment: "Total number of capital calls"
    - name: "default_count"
      expr: SUM(CASE WHEN is_default = TRUE THEN 1 ELSE 0 END)
      comment: "Number of defaulted capital calls"
    - name: "investor_count"
      expr: COUNT(DISTINCT investor_id)
      comment: "Number of distinct investors receiving capital calls"
    - name: "fund_count"
      expr: COUNT(DISTINCT fund_id)
      comment: "Number of distinct funds issuing capital calls"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_distribution`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Investment distribution metrics tracking cash flows to investors including return of capital, income, and gains for waterfall execution and tax reporting"
  source: "`real_estate_ecm`.`investment`.`investment_distribution`"
  dimensions:
    - name: "distribution_status"
      expr: distribution_status
      comment: "Status of distribution (declared, paid, cancelled)"
    - name: "distribution_type"
      expr: distribution_type
      comment: "Type of distribution (operating, capital gain, return of capital, liquidating)"
    - name: "frequency"
      expr: frequency
      comment: "Distribution frequency (monthly, quarterly, annual, ad-hoc)"
    - name: "payment_method"
      expr: payment_method
      comment: "Method of distribution payment (wire, ACH, check, reinvestment)"
    - name: "reinvestment_elected"
      expr: reinvestment_elected
      comment: "Whether investor elected to reinvest distribution"
    - name: "k1_issued"
      expr: k1_issued
      comment: "Whether K-1 tax form has been issued for distribution"
    - name: "tax_year"
      expr: tax_year
      comment: "Tax year of distribution"
    - name: "distribution_year"
      expr: YEAR(distribution_date)
      comment: "Calendar year of distribution payment"
    - name: "distribution_quarter"
      expr: CONCAT('Q', QUARTER(distribution_date), '-', YEAR(distribution_date))
      comment: "Calendar quarter of distribution payment"
  measures:
    - name: "total_gross_amount"
      expr: SUM(CAST(gross_amount AS DOUBLE))
      comment: "Total gross distribution amount before withholding"
    - name: "total_net_amount"
      expr: SUM(CAST(net_amount AS DOUBLE))
      comment: "Total net distribution amount after withholding"
    - name: "total_return_of_capital"
      expr: SUM(CAST(return_of_capital_amount AS DOUBLE))
      comment: "Total return of capital component of distributions"
    - name: "total_capital_gain"
      expr: SUM(CAST(capital_gain_amount AS DOUBLE))
      comment: "Total capital gain component of distributions"
    - name: "total_preferred_return"
      expr: SUM(CAST(preferred_return_amount AS DOUBLE))
      comment: "Total preferred return component of distributions"
    - name: "total_carried_interest"
      expr: SUM(CAST(carried_interest_amount AS DOUBLE))
      comment: "Total carried interest component of distributions"
    - name: "total_ffo_component"
      expr: SUM(CAST(ffo_component_amount AS DOUBLE))
      comment: "Total funds from operations component of distributions"
    - name: "total_affo_component"
      expr: SUM(CAST(affo_component_amount AS DOUBLE))
      comment: "Total adjusted funds from operations component of distributions"
    - name: "total_withholding_tax"
      expr: SUM(CAST(withholding_tax_amount AS DOUBLE))
      comment: "Total withholding tax on distributions"
    - name: "avg_withholding_tax_rate"
      expr: AVG(CAST(withholding_tax_rate AS DOUBLE))
      comment: "Average withholding tax rate on distributions"
    - name: "total_reinvestment_amount"
      expr: SUM(CAST(reinvestment_units AS DOUBLE) * CAST(reinvestment_price_per_unit AS DOUBLE))
      comment: "Total amount reinvested by investors"
    - name: "distribution_count"
      expr: COUNT(1)
      comment: "Total number of distributions"
    - name: "investor_count"
      expr: COUNT(DISTINCT investor_id)
      comment: "Number of distinct investors receiving distributions"
    - name: "fund_count"
      expr: COUNT(DISTINCT fund_id)
      comment: "Number of distinct funds making distributions"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_commitment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Investor commitment metrics tracking pledged capital, drawdowns, and distributions for fundraising performance and capital availability analysis"
  source: "`real_estate_ecm`.`investment`.`commitment`"
  dimensions:
    - name: "commitment_status"
      expr: commitment_status
      comment: "Status of investor commitment (active, defaulted, transferred, terminated)"
    - name: "capital_call_schedule_type"
      expr: capital_call_schedule_type
      comment: "Type of capital call schedule (as-needed, scheduled, milestone-based)"
    - name: "management_fee_basis"
      expr: management_fee_basis
      comment: "Basis for management fee calculation (committed capital, invested capital, NAV)"
    - name: "co_investment_flag"
      expr: co_investment_flag
      comment: "Whether commitment includes co-investment rights"
    - name: "side_letter_flag"
      expr: side_letter_flag
      comment: "Whether commitment has side letter terms"
    - name: "erisa_flag"
      expr: erisa_flag
      comment: "Whether investor is ERISA-governed"
    - name: "tax_exempt_flag"
      expr: tax_exempt_flag
      comment: "Whether investor is tax-exempt"
    - name: "commitment_year"
      expr: YEAR(commitment_date)
      comment: "Calendar year of commitment"
    - name: "close_year"
      expr: YEAR(close_date)
      comment: "Calendar year of fund close"
  measures:
    - name: "total_commitment_amount"
      expr: SUM(CAST(amount AS DOUBLE))
      comment: "Total committed capital from investors"
    - name: "total_called_capital"
      expr: SUM(CAST(called_capital_amount AS DOUBLE))
      comment: "Total capital called from investors"
    - name: "total_uncalled_capital"
      expr: SUM(CAST(uncalled_capital_amount AS DOUBLE))
      comment: "Total uncalled capital remaining"
    - name: "total_distributed_capital"
      expr: SUM(CAST(distributed_capital_amount AS DOUBLE))
      comment: "Total capital distributed to investors"
    - name: "total_recallable_distributions"
      expr: SUM(CAST(recallable_distributions_amount AS DOUBLE))
      comment: "Total distributions subject to recallability"
    - name: "total_aum_contribution"
      expr: SUM(CAST(aum_contribution_amount AS DOUBLE))
      comment: "Total contribution to assets under management"
    - name: "avg_management_fee_rate"
      expr: AVG(CAST(management_fee_rate AS DOUBLE))
      comment: "Average management fee rate across commitments"
    - name: "avg_carried_interest_rate"
      expr: AVG(CAST(carried_interest_rate AS DOUBLE))
      comment: "Average carried interest rate across commitments"
    - name: "avg_preferred_return_rate"
      expr: AVG(CAST(preferred_return_rate AS DOUBLE))
      comment: "Average preferred return rate across commitments"
    - name: "commitment_count"
      expr: COUNT(1)
      comment: "Total number of investor commitments"
    - name: "investor_count"
      expr: COUNT(DISTINCT commitment_investor_id)
      comment: "Number of distinct investors with commitments"
    - name: "fund_count"
      expr: COUNT(DISTINCT fund_id)
      comment: "Number of distinct funds with commitments"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_debt_facility`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Debt facility metrics tracking leverage, covenant compliance, and debt service for capital structure management and risk monitoring"
  source: "`real_estate_ecm`.`investment`.`debt_facility`"
  dimensions:
    - name: "facility_status"
      expr: facility_status
      comment: "Status of debt facility (active, matured, refinanced, defaulted)"
    - name: "facility_type"
      expr: facility_type
      comment: "Type of debt facility (term loan, revolver, construction, bridge)"
    - name: "interest_rate_type"
      expr: interest_rate_type
      comment: "Type of interest rate (fixed, floating, hybrid)"
    - name: "recourse_type"
      expr: recourse_type
      comment: "Recourse type (non-recourse, recourse, limited recourse)"
    - name: "seniority_tier"
      expr: seniority_tier
      comment: "Seniority tier of debt (senior, mezzanine, subordinated)"
    - name: "covenant_compliance_status"
      expr: covenant_compliance_status
      comment: "Covenant compliance status (compliant, watch, breach, waived)"
    - name: "is_cross_collateralized"
      expr: is_cross_collateralized
      comment: "Whether facility is cross-collateralized"
    - name: "is_cross_defaulted"
      expr: is_cross_defaulted
      comment: "Whether facility has cross-default provisions"
    - name: "origination_year"
      expr: YEAR(origination_date)
      comment: "Calendar year of debt origination"
    - name: "maturity_year"
      expr: YEAR(maturity_date)
      comment: "Calendar year of debt maturity"
  measures:
    - name: "total_commitment_amount"
      expr: SUM(CAST(commitment_amount AS DOUBLE))
      comment: "Total committed debt facility amount"
    - name: "total_outstanding_balance"
      expr: SUM(CAST(outstanding_balance AS DOUBLE))
      comment: "Total outstanding debt balance"
    - name: "total_unfunded_commitment"
      expr: SUM(CAST(unfunded_commitment AS DOUBLE))
      comment: "Total unfunded commitment available for drawdown"
    - name: "avg_interest_rate"
      expr: AVG(CAST(interest_rate AS DOUBLE))
      comment: "Average interest rate across debt facilities"
    - name: "avg_rate_spread"
      expr: AVG(CAST(rate_spread AS DOUBLE))
      comment: "Average spread over index rate"
    - name: "avg_ltv_ratio"
      expr: AVG(CAST(ltv_ratio AS DOUBLE))
      comment: "Average loan-to-value ratio across facilities"
    - name: "avg_dscr"
      expr: AVG(CAST(dscr AS DOUBLE))
      comment: "Average debt service coverage ratio across facilities"
    - name: "avg_covenant_ltv_threshold"
      expr: AVG(CAST(covenant_ltv_threshold AS DOUBLE))
      comment: "Average LTV covenant threshold"
    - name: "avg_covenant_dscr_threshold"
      expr: AVG(CAST(covenant_dscr_threshold AS DOUBLE))
      comment: "Average DSCR covenant threshold"
    - name: "facility_count"
      expr: COUNT(1)
      comment: "Total number of debt facilities"
    - name: "lender_count"
      expr: COUNT(DISTINCT lender_id)
      comment: "Number of distinct lenders"
    - name: "fund_count"
      expr: COUNT(DISTINCT fund_id)
      comment: "Number of distinct funds with debt facilities"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_portfolio_asset`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Portfolio asset metrics tracking acquisition cost, equity invested, unrealized gains, and performance targets for portfolio construction and rebalancing decisions"
  source: "`real_estate_ecm`.`investment`.`portfolio_asset`"
  dimensions:
    - name: "asset_status"
      expr: asset_status
      comment: "Status of portfolio asset (active, under contract, disposed, held for sale)"
    - name: "hold_strategy"
      expr: hold_strategy
      comment: "Hold strategy for asset (core, core-plus, value-add, opportunistic)"
    - name: "investment_risk_profile"
      expr: investment_risk_profile
      comment: "Risk profile of investment (low, moderate, high)"
    - name: "is_encumbered"
      expr: is_encumbered
      comment: "Whether asset is encumbered by debt"
    - name: "is_joint_venture"
      expr: is_joint_venture
      comment: "Whether asset is held in joint venture"
    - name: "geographic_market"
      expr: geographic_market
      comment: "Geographic market of asset"
    - name: "country_code"
      expr: country_code
      comment: "Country code of asset location"
    - name: "acquisition_year"
      expr: YEAR(acquisition_date)
      comment: "Calendar year of asset acquisition"
  measures:
    - name: "total_acquisition_cost"
      expr: SUM(CAST(acquisition_cost AS DOUBLE))
      comment: "Total acquisition cost of portfolio assets"
    - name: "total_equity_invested"
      expr: SUM(CAST(equity_invested AS DOUBLE))
      comment: "Total equity invested in portfolio assets"
    - name: "total_allocated_debt"
      expr: SUM(CAST(allocated_debt AS DOUBLE))
      comment: "Total debt allocated to portfolio assets"
    - name: "total_current_book_value"
      expr: SUM(CAST(current_book_value AS DOUBLE))
      comment: "Total current book value of portfolio assets"
    - name: "total_appraised_value"
      expr: SUM(CAST(appraised_value AS DOUBLE))
      comment: "Total appraised value of portfolio assets"
    - name: "total_disposition_price"
      expr: SUM(CAST(disposition_price AS DOUBLE))
      comment: "Total disposition price of sold assets"
    - name: "total_unrealized_gain_loss"
      expr: SUM(CAST(unrealized_gain_loss AS DOUBLE))
      comment: "Total unrealized gain or loss on portfolio assets"
    - name: "total_in_place_noi"
      expr: SUM(CAST(in_place_noi AS DOUBLE))
      comment: "Total in-place net operating income"
    - name: "total_stabilized_noi"
      expr: SUM(CAST(stabilized_noi AS DOUBLE))
      comment: "Total stabilized net operating income"
    - name: "total_capex_budget"
      expr: SUM(CAST(capex_budget AS DOUBLE))
      comment: "Total capital expenditure budget"
    - name: "total_capex_spent"
      expr: SUM(CAST(capex_spent_to_date AS DOUBLE))
      comment: "Total capital expenditure spent to date"
    - name: "avg_occupancy_rate"
      expr: AVG(CAST(occupancy_rate AS DOUBLE))
      comment: "Average occupancy rate across portfolio assets"
    - name: "avg_ownership_percentage"
      expr: AVG(CAST(ownership_percentage AS DOUBLE))
      comment: "Average ownership percentage across portfolio assets"
    - name: "avg_target_irr"
      expr: AVG(CAST(target_irr AS DOUBLE))
      comment: "Average target IRR across portfolio assets"
    - name: "avg_target_equity_multiple"
      expr: AVG(CAST(target_equity_multiple AS DOUBLE))
      comment: "Average target equity multiple across portfolio assets"
    - name: "avg_target_cap_rate"
      expr: AVG(CAST(target_cap_rate AS DOUBLE))
      comment: "Average target capitalization rate across portfolio assets"
    - name: "asset_count"
      expr: COUNT(1)
      comment: "Total number of portfolio assets"
    - name: "portfolio_count"
      expr: COUNT(DISTINCT portfolio_id)
      comment: "Number of distinct portfolios"
$$;

CREATE OR REPLACE VIEW `real_estate_ecm`.`_metrics`.`investment_deal`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Investment deal pipeline metrics tracking deal flow, pricing, underwriting, and IC decisions for acquisition strategy and capital deployment analysis"
  source: "`real_estate_ecm`.`investment`.`investment_deal`"
  dimensions:
    - name: "deal_status"
      expr: deal_status
      comment: "Status of investment deal (active, closed, dead, on-hold)"
    - name: "deal_type"
      expr: deal_type
      comment: "Type of investment deal (acquisition, disposition, refinance, development)"
    - name: "stage"
      expr: stage
      comment: "Stage of deal pipeline (sourcing, underwriting, LOI, due diligence, closing)"
    - name: "ic_decision"
      expr: ic_decision
      comment: "Investment committee decision (approved, declined, deferred, conditional)"
    - name: "ic_recommendation"
      expr: ic_recommendation
      comment: "Investment committee recommendation"
    - name: "is_off_market"
      expr: is_off_market
      comment: "Whether deal was sourced off-market"
    - name: "dead_reason"
      expr: dead_reason
      comment: "Reason deal was marked dead"
    - name: "sourced_year"
      expr: YEAR(sourced_date)
      comment: "Calendar year deal was sourced"
    - name: "close_year"
      expr: YEAR(actual_close_date)
      comment: "Calendar year deal closed"
  measures:
    - name: "total_asking_price"
      expr: SUM(CAST(asking_price AS DOUBLE))
      comment: "Total asking price across deals"
    - name: "total_contracted_price"
      expr: SUM(CAST(contracted_price AS DOUBLE))
      comment: "Total contracted price across deals"
    - name: "total_underwritten_value"
      expr: SUM(CAST(underwritten_value AS DOUBLE))
      comment: "Total underwritten value across deals"
    - name: "total_underwritten_equity"
      expr: SUM(CAST(underwritten_equity_amount AS DOUBLE))
      comment: "Total underwritten equity amount across deals"
    - name: "total_underwritten_debt"
      expr: SUM(CAST(underwritten_debt_amount AS DOUBLE))
      comment: "Total underwritten debt amount across deals"
    - name: "total_underwritten_noi"
      expr: SUM(CAST(underwritten_noi AS DOUBLE))
      comment: "Total underwritten net operating income across deals"
    - name: "avg_target_irr"
      expr: AVG(CAST(target_irr AS DOUBLE))
      comment: "Average target IRR across deals"
    - name: "avg_target_equity_multiple"
      expr: AVG(CAST(target_equity_multiple AS DOUBLE))
      comment: "Average target equity multiple across deals"
    - name: "avg_target_cap_rate"
      expr: AVG(CAST(target_cap_rate AS DOUBLE))
      comment: "Average target capitalization rate across deals"
    - name: "avg_underwritten_ltv"
      expr: AVG(CAST(underwritten_ltv AS DOUBLE))
      comment: "Average underwritten loan-to-value ratio across deals"
    - name: "avg_hold_period_years"
      expr: AVG(CAST(hold_period_years AS DOUBLE))
      comment: "Average hold period in years across deals"
    - name: "deal_count"
      expr: COUNT(1)
      comment: "Total number of investment deals"
    - name: "fund_count"
      expr: COUNT(DISTINCT fund_id)
      comment: "Number of distinct funds with deals"
    - name: "portfolio_count"
      expr: COUNT(DISTINCT portfolio_id)
      comment: "Number of distinct portfolios with deals"
$$;