-- Metric views for domain: trade | Business: Food Beverage | Version: 1 | Generated on: 2026-05-05 21:55:54

CREATE OR REPLACE VIEW `food_beverage_ecm`.`_metrics`.`trade_promotion_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Core KPI view for promotion events covering revenue performance and volume"
  source: "`food_beverage_ecm`.`trade`.`promotion_event`"
  dimensions:
    - name: "promotion_type"
      expr: promotion_type
      comment: "Type of promotion (e.g., discount, bundle)"
  measures:
    - name: "promotion_event_count"
      expr: COUNT(1)
      comment: "Number of promotion events"
    - name: "total_actual_revenue"
      expr: SUM(CAST(actual_revenue AS DOUBLE))
      comment: "Sum of actual revenue generated by promotion events"
    - name: "total_target_revenue"
      expr: SUM(CAST(target_revenue AS DOUBLE))
      comment: "Sum of target revenue set for promotion events"
    - name: "average_actual_revenue"
      expr: AVG(CAST(actual_revenue AS DOUBLE))
      comment: "Average actual revenue per promotion event"
$$;

CREATE OR REPLACE VIEW `food_beverage_ecm`.`_metrics`.`trade_promotion_line`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "KPIs for individual promotion lines, focusing on funding efficiency and margin"
  source: "`food_beverage_ecm`.`trade`.`promotion_line`"
  dimensions:
    - name: "promotion_type"
      expr: promotion_type
      comment: "Promotion line type (e.g., price, feature)"
  measures:
    - name: "promotion_line_count"
      expr: COUNT(1)
      comment: "Number of promotion line records"
    - name: "total_funding_amount"
      expr: SUM(CAST(total_funding_amount AS DOUBLE))
      comment: "Total funding allocated to promotion lines"
    - name: "total_quantity"
      expr: SUM(CAST(quantity AS DOUBLE))
      comment: "Total quantity of SKU units promoted"
    - name: "average_margin_per_unit"
      expr: AVG(CAST(margin_per_unit AS DOUBLE))
      comment: "Average margin per unit across promotion lines"
$$;

CREATE OR REPLACE VIEW `food_beverage_ecm`.`_metrics`.`trade_settlement`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Financial settlement performance metrics"
  source: "`food_beverage_ecm`.`trade`.`settlement`"
  dimensions:
    - name: "settlement_status"
      expr: settlement_status
      comment: "Current status of the settlement"
  measures:
    - name: "settlement_count"
      expr: COUNT(1)
      comment: "Number of settlement records"
    - name: "total_net_amount"
      expr: SUM(CAST(net_amount AS DOUBLE))
      comment: "Total net amount settled"
    - name: "total_gross_amount"
      expr: SUM(CAST(gross_amount AS DOUBLE))
      comment: "Total gross amount settled"
    - name: "average_net_amount"
      expr: AVG(CAST(net_amount AS DOUBLE))
      comment: "Average net amount per settlement"
$$;

CREATE OR REPLACE VIEW `food_beverage_ecm`.`_metrics`.`trade_fund`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Fund allocation and utilization metrics"
  source: "`food_beverage_ecm`.`trade`.`fund`"
  dimensions:
    - name: "fund_type"
      expr: fund_type
      comment: "Classification of the fund (e.g., promotional, research)"
  measures:
    - name: "fund_count"
      expr: COUNT(1)
      comment: "Number of fund records"
    - name: "total_accrued_amount"
      expr: SUM(CAST(accrued_amount AS DOUBLE))
      comment: "Total amount accrued to funds"
    - name: "total_paid_amount"
      expr: SUM(CAST(paid_amount AS DOUBLE))
      comment: "Total amount paid from funds"
    - name: "average_accrued_amount"
      expr: AVG(CAST(accrued_amount AS DOUBLE))
      comment: "Average accrued amount per fund"
$$;

CREATE OR REPLACE VIEW `food_beverage_ecm`.`_metrics`.`trade_accrual`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Accrual financial impact metrics"
  source: "`food_beverage_ecm`.`trade`.`accrual`"
  dimensions:
    - name: "accrual_status"
      expr: accrual_status
      comment: "Current status of the accrual"
  measures:
    - name: "accrual_count"
      expr: COUNT(1)
      comment: "Number of accrual records"
    - name: "total_amount"
      expr: SUM(CAST(amount AS DOUBLE))
      comment: "Total accrual amount"
    - name: "total_net_sales_amount"
      expr: SUM(CAST(net_sales_amount AS DOUBLE))
      comment: "Total net sales amount linked to accruals"
    - name: "average_amount"
      expr: AVG(CAST(amount AS DOUBLE))
      comment: "Average accrual amount per record"
$$;