-- Metric views for domain: commercial | Business: Genomics Biotech | Version: 1 | Generated on: 2026-05-06 12:58:41

CREATE OR REPLACE VIEW `genomics_biotech_ecm`.`_metrics`.`commercial_campaign_performance`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Key financial performance of marketing campaigns"
  source: "`genomics_biotech_ecm`.`commercial`.`campaign`"
  dimensions:
    - name: "campaign_status"
      expr: campaign_status
      comment: "Current status of the campaign (e.g., Active, Completed)"
    - name: "campaign_type"
      expr: campaign_type
      comment: "Type of campaign (e.g., Webinar, Conference, Digital)"
    - name: "channel_mix"
      expr: channel_mix
      comment: "Channels used in the campaign (e.g., Email, Social, In‑person)"
    - name: "geographic_scope"
      expr: geographic_scope
      comment: "Geographic scope of the campaign"
    - name: "campaign_month"
      expr: DATE_TRUNC('month', actual_start_date)
      comment: "Month the campaign started"
  measures:
    - name: "campaign_count"
      expr: COUNT(1)
      comment: "Number of campaign records"
    - name: "total_actual_revenue"
      expr: SUM(CAST(actual_revenue_amount AS DOUBLE))
      comment: "Sum of actual revenue generated by campaigns"
    - name: "total_budget_allocated"
      expr: SUM(CAST(budget_allocated_amount AS DOUBLE))
      comment: "Total budget allocated to campaigns"
    - name: "total_budget_spent"
      expr: SUM(CAST(budget_spent_amount AS DOUBLE))
      comment: "Total budget actually spent by campaigns"
$$;

CREATE OR REPLACE VIEW `genomics_biotech_ecm`.`_metrics`.`commercial_opportunity_pipeline`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Pipeline health and revenue potential of sales opportunities"
  source: "`genomics_biotech_ecm`.`commercial`.`opportunity`"
  dimensions:
    - name: "opportunity_stage"
      expr: stage
      comment: "Current sales stage of the opportunity"
    - name: "sales_territory_id"
      expr: territory_id
      comment: "Territory responsible for the opportunity"
    - name: "market_segment_target_id"
      expr: market_segment_target_id
      comment: "Target market segment for the opportunity"
    - name: "fiscal_quarter"
      expr: fiscal_quarter
      comment: "Fiscal quarter of the opportunity"
    - name: "fiscal_year"
      expr: fiscal_year
      comment: "Fiscal year of the opportunity"
  measures:
    - name: "total_opportunity_count"
      expr: COUNT(1)
      comment: "Total number of opportunities"
    - name: "won_opportunity_count"
      expr: COUNT(CASE WHEN is_won THEN 1 END)
      comment: "Number of opportunities marked as won"
    - name: "total_arr"
      expr: SUM(CAST(arr AS DOUBLE))
      comment: "Sum of Annual Recurring Revenue (ARR) for all opportunities"
    - name: "total_tcv"
      expr: SUM(CAST(tcv AS DOUBLE))
      comment: "Sum of Total Contract Value (TCV) for all opportunities"
    - name: "total_discount_percentage"
      expr: SUM(CAST(discount_percentage AS DOUBLE))
      comment: "Aggregate discount percentage applied across opportunities"
$$;

CREATE OR REPLACE VIEW `genomics_biotech_ecm`.`_metrics`.`commercial_lead_generation`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Lead acquisition and conversion performance"
  source: "`genomics_biotech_ecm`.`commercial`.`lead`"
  dimensions:
    - name: "lead_source"
      expr: lead_source
      comment: "Origin of the lead (e.g., Web, Trade Show, Referral)"
    - name: "lead_status"
      expr: lead_status
      comment: "Current status of the lead"
    - name: "market_segment_target_id"
      expr: market_segment_target_id
      comment: "Target market segment for the lead"
    - name: "geographic_region"
      expr: geographic_region
      comment: "Geographic region of the lead"
    - name: "lead_created_month"
      expr: DATE_TRUNC('month', created_timestamp)
      comment: "Month the lead record was created"
  measures:
    - name: "total_leads"
      expr: COUNT(1)
      comment: "Total number of leads captured"
    - name: "converted_leads"
      expr: COUNT(CASE WHEN is_converted THEN 1 END)
      comment: "Number of leads that converted to an opportunity or customer"
    - name: "total_annual_revenue"
      expr: SUM(CAST(annual_revenue AS DOUBLE))
      comment: "Sum of projected annual revenue associated with leads"
$$;

CREATE OR REPLACE VIEW `genomics_biotech_ecm`.`_metrics`.`commercial_sales_quota`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Quota allocation and attainment overview"
  source: "`genomics_biotech_ecm`.`commercial`.`sales_quota`"
  dimensions:
    - name: "fiscal_year"
      expr: fiscal_year
      comment: "Fiscal year of the quota"
    - name: "fiscal_quarter"
      expr: fiscal_quarter
      comment: "Fiscal quarter of the quota"
    - name: "sales_holder_employee_id"
      expr: sales_holder_employee_id
      comment: "Employee holding the quota"
  measures:
    - name: "quota_record_count"
      expr: COUNT(1)
      comment: "Number of quota records"
    - name: "total_quota_amount"
      expr: SUM(CAST(quota_amount AS DOUBLE))
      comment: "Total quota amount assigned"
    - name: "total_base_quota_amount"
      expr: SUM(CAST(base_quota_amount AS DOUBLE))
      comment: "Sum of base quota amounts"
    - name: "total_stretch_quota_amount"
      expr: SUM(CAST(stretch_quota_amount AS DOUBLE))
      comment: "Sum of stretch quota amounts"
$$;

CREATE OR REPLACE VIEW `genomics_biotech_ecm`.`_metrics`.`commercial_contract_value`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Financial impact of signed contracts"
  source: "`genomics_biotech_ecm`.`commercial`.`contract`"
  dimensions:
    - name: "contract_status"
      expr: contract_status
      comment: "Current status of the contract (e.g., Active, Expired)"
    - name: "contract_type"
      expr: contract_type
      comment: "Type of contract (e.g., Service, Supply)"
    - name: "contract_month"
      expr: DATE_TRUNC('month', effective_date)
      comment: "Month the contract became effective"
    - name: "sales_territory_id"
      expr: sales_territory_id
      comment: "Territory responsible for the contract"
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the contract amounts"
  measures:
    - name: "contract_count"
      expr: COUNT(1)
      comment: "Number of contracts"
    - name: "total_contract_value"
      expr: SUM(CAST(total_contract_value AS DOUBLE))
      comment: "Sum of total contract value across all contracts"
    - name: "average_contract_value"
      expr: AVG(CAST(total_contract_value AS DOUBLE))
      comment: "Average contract value"
$$;