-- Metric views for domain: fleet | Business: Transport Shipping | Version: 1 | Generated on: 2026-05-08 19:31:38

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_asset_utilisation`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Fleet asset utilisation KPIs measuring operational efficiency, capacity usage, and cost-effectiveness of transport assets across the fleet."
  source: "`transport_shipping_ecm`.`fleet`.`asset_utilisation`"
  dimensions:
    - name: "operational_status"
      expr: operational_status
      comment: "Current operational status of the asset (active, idle, maintenance, etc.)"
    - name: "period_type"
      expr: period_type
      comment: "Reporting period granularity (daily, weekly, monthly)"
    - name: "reporting_period_date"
      expr: DATE_TRUNC('month', reporting_period_date)
      comment: "Reporting period truncated to month for trend analysis"
    - name: "compliance_status"
      expr: compliance_status
      comment: "Compliance status of the asset during the reporting period"
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of financial measures"
  measures:
    - name: "avg_utilisation_rate_pct"
      expr: AVG(CAST(utilisation_rate_percent AS DOUBLE))
      comment: "Average fleet utilisation rate - key indicator of asset productivity and ROI"
    - name: "avg_load_factor_pct"
      expr: AVG(CAST(load_factor_percent AS DOUBLE))
      comment: "Average load factor percentage indicating how well payload capacity is being used"
    - name: "total_distance_travelled_km"
      expr: SUM(CAST(distance_travelled_km AS DOUBLE))
      comment: "Total distance travelled across fleet for activity volume measurement"
    - name: "total_fuel_consumed_liters"
      expr: SUM(CAST(fuel_consumed_liters AS DOUBLE))
      comment: "Total fuel consumption across fleet for cost and sustainability tracking"
    - name: "total_co2_emissions_kg"
      expr: SUM(CAST(co2_emissions_kg AS DOUBLE))
      comment: "Total CO2 emissions for environmental compliance and sustainability reporting"
    - name: "avg_fuel_efficiency_l_per_100km"
      expr: AVG(CAST(fuel_efficiency_liters_per_100km AS DOUBLE))
      comment: "Average fuel efficiency across fleet - key cost driver and sustainability metric"
    - name: "total_revenue_generated"
      expr: SUM(CAST(revenue_generated AS DOUBLE))
      comment: "Total revenue generated by fleet assets for profitability analysis"
    - name: "total_operating_cost"
      expr: SUM(CAST(operating_cost AS DOUBLE))
      comment: "Total operating cost of fleet assets for cost management"
    - name: "avg_on_time_delivery_rate_pct"
      expr: AVG(CAST(on_time_delivery_rate_percent AS DOUBLE))
      comment: "Average on-time delivery rate - critical service quality KPI"
    - name: "total_operational_hours"
      expr: SUM(CAST(total_operational_hours AS DOUBLE))
      comment: "Total operational hours across fleet for capacity planning"
    - name: "total_downtime_hours"
      expr: SUM(CAST(total_downtime_hours AS DOUBLE))
      comment: "Total downtime hours indicating fleet availability loss"
    - name: "total_maintenance_hours"
      expr: SUM(CAST(total_maintenance_hours AS DOUBLE))
      comment: "Total maintenance hours for maintenance burden analysis"
    - name: "asset_count"
      expr: COUNT(DISTINCT transport_asset_id)
      comment: "Count of distinct assets with utilisation records for fleet size tracking"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_trip`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Trip-level operational metrics measuring delivery performance, revenue, fuel efficiency, and emissions per trip for operational steering."
  source: "`transport_shipping_ecm`.`fleet`.`trip`"
  dimensions:
    - name: "trip_status"
      expr: status
      comment: "Current status of the trip (planned, in-progress, completed, cancelled)"
    - name: "cargo_type"
      expr: cargo_type
      comment: "Type of cargo being transported for segment analysis"
    - name: "origin_location_code"
      expr: origin_location_code
      comment: "Origin location for route-based analysis"
    - name: "destination_location_code"
      expr: destination_location_code
      comment: "Destination location for route-based analysis"
    - name: "priority_level"
      expr: priority_level
      comment: "Trip priority level for service tier analysis"
    - name: "is_expedited"
      expr: is_expedited
      comment: "Whether the trip is expedited for premium service tracking"
    - name: "trip_month"
      expr: DATE_TRUNC('month', actual_start_timestamp)
      comment: "Trip start month for temporal trend analysis"
  measures:
    - name: "total_trips"
      expr: COUNT(1)
      comment: "Total number of trips for volume tracking"
    - name: "total_gross_revenue"
      expr: SUM(CAST(gross_amount AS DOUBLE))
      comment: "Total gross revenue from trips for financial performance"
    - name: "total_net_revenue"
      expr: SUM(CAST(net_amount AS DOUBLE))
      comment: "Total net revenue from trips after deductions"
    - name: "total_distance_km"
      expr: SUM(CAST(distance_km AS DOUBLE))
      comment: "Total distance covered across all trips"
    - name: "total_fuel_consumed_liters"
      expr: SUM(CAST(fuel_consumed_liters AS DOUBLE))
      comment: "Total fuel consumed across trips for cost and sustainability"
    - name: "total_emissions_kg_co2"
      expr: SUM(CAST(emissions_kg_co2 AS DOUBLE))
      comment: "Total CO2 emissions from trips for environmental reporting"
    - name: "avg_distance_per_trip_km"
      expr: AVG(CAST(distance_km AS DOUBLE))
      comment: "Average distance per trip for route efficiency analysis"
    - name: "avg_speed_kmh"
      expr: AVG(CAST(average_speed_kmh AS DOUBLE))
      comment: "Average speed across trips for operational efficiency"
    - name: "total_cargo_weight_kg"
      expr: SUM(CAST(cargo_weight_kg AS DOUBLE))
      comment: "Total cargo weight transported for throughput measurement"
    - name: "avg_gross_amount_per_trip"
      expr: AVG(CAST(gross_amount AS DOUBLE))
      comment: "Average revenue per trip for yield management"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_fuel_transaction`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Fuel transaction metrics for cost management, consumption analysis, and carbon emissions tracking across the fleet."
  source: "`transport_shipping_ecm`.`fleet`.`fuel_transaction`"
  dimensions:
    - name: "fuel_type"
      expr: fuel_type
      comment: "Type of fuel (diesel, petrol, LNG, electric, etc.) for energy mix analysis"
    - name: "fuel_grade"
      expr: fuel_grade
      comment: "Grade of fuel for quality and cost analysis"
    - name: "fuel_station_country_code"
      expr: fuel_station_country_code
      comment: "Country where fueling occurred for geographic cost analysis"
    - name: "payment_method"
      expr: payment_method
      comment: "Payment method used for reconciliation tracking"
    - name: "transaction_status"
      expr: transaction_status
      comment: "Status of the fuel transaction"
    - name: "transaction_month"
      expr: DATE_TRUNC('month', transaction_datetime)
      comment: "Transaction month for trend analysis"
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the transaction for multi-currency reporting"
  measures:
    - name: "total_fuel_cost"
      expr: SUM(CAST(total_cost AS DOUBLE))
      comment: "Total fuel expenditure - major fleet operating cost component"
    - name: "total_fuel_quantity"
      expr: SUM(CAST(quantity AS DOUBLE))
      comment: "Total fuel volume purchased across fleet"
    - name: "avg_unit_cost"
      expr: AVG(CAST(unit_cost AS DOUBLE))
      comment: "Average fuel unit cost for procurement benchmarking"
    - name: "total_co2e_emissions_kg"
      expr: SUM(CAST(co2e_emissions_kg AS DOUBLE))
      comment: "Total CO2-equivalent emissions from fuel consumption for sustainability reporting"
    - name: "total_tax_amount"
      expr: SUM(CAST(tax_amount AS DOUBLE))
      comment: "Total fuel tax paid for fiscal reporting"
    - name: "total_discount_amount"
      expr: SUM(CAST(discount_amount AS DOUBLE))
      comment: "Total discounts received on fuel for procurement effectiveness"
    - name: "avg_fuel_efficiency"
      expr: AVG(CAST(fuel_efficiency AS DOUBLE))
      comment: "Average fuel efficiency per transaction for fleet performance benchmarking"
    - name: "transaction_count"
      expr: COUNT(1)
      comment: "Number of fuel transactions for activity volume tracking"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_maintenance_order`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Maintenance order metrics for fleet reliability, cost control, and preventive maintenance effectiveness."
  source: "`transport_shipping_ecm`.`fleet`.`maintenance_order`"
  dimensions:
    - name: "maintenance_type"
      expr: maintenance_type
      comment: "Type of maintenance (preventive, corrective, emergency) for strategy analysis"
    - name: "maintenance_category"
      expr: maintenance_category
      comment: "Category of maintenance work performed"
    - name: "maintenance_order_status"
      expr: maintenance_order_status
      comment: "Current status of the maintenance order"
    - name: "priority"
      expr: priority
      comment: "Priority level of the maintenance order"
    - name: "maintenance_provider_type"
      expr: maintenance_provider_type
      comment: "Whether maintenance is internal or external for cost analysis"
    - name: "post_maintenance_status"
      expr: post_maintenance_status
      comment: "Asset status after maintenance completion"
    - name: "raised_month"
      expr: DATE_TRUNC('month', raised_date)
      comment: "Month the maintenance order was raised for trend analysis"
    - name: "warranty_claim_flag"
      expr: warranty_claim_flag
      comment: "Whether maintenance is covered under warranty"
  measures:
    - name: "total_maintenance_cost"
      expr: SUM(CAST(total_maintenance_cost AS DOUBLE))
      comment: "Total maintenance expenditure for budget management"
    - name: "total_labor_cost"
      expr: SUM(CAST(labor_cost AS DOUBLE))
      comment: "Total labor cost component of maintenance"
    - name: "total_parts_cost"
      expr: SUM(CAST(parts_cost AS DOUBLE))
      comment: "Total parts cost component of maintenance"
    - name: "total_external_service_cost"
      expr: SUM(CAST(external_service_cost AS DOUBLE))
      comment: "Total external service provider costs"
    - name: "total_downtime_hours"
      expr: SUM(CAST(downtime_hours AS DOUBLE))
      comment: "Total downtime hours caused by maintenance - key availability metric"
    - name: "total_labor_hours"
      expr: SUM(CAST(labor_hours AS DOUBLE))
      comment: "Total labor hours spent on maintenance"
    - name: "avg_maintenance_cost_per_order"
      expr: AVG(CAST(total_maintenance_cost AS DOUBLE))
      comment: "Average cost per maintenance order for benchmarking"
    - name: "avg_downtime_hours_per_order"
      expr: AVG(CAST(downtime_hours AS DOUBLE))
      comment: "Average downtime per maintenance event for availability planning"
    - name: "maintenance_order_count"
      expr: COUNT(1)
      comment: "Total number of maintenance orders for workload tracking"
    - name: "distinct_assets_maintained"
      expr: COUNT(DISTINCT transport_asset_id)
      comment: "Number of distinct assets requiring maintenance"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_driver_performance`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Driver performance metrics for safety management, fuel efficiency coaching, and operational excellence programs."
  source: "`transport_shipping_ecm`.`fleet`.`driver_performance`"
  dimensions:
    - name: "evaluation_type"
      expr: evaluation_type
      comment: "Type of performance evaluation conducted"
    - name: "evaluation_status"
      expr: evaluation_status
      comment: "Status of the performance evaluation"
    - name: "safety_rating"
      expr: safety_rating
      comment: "Driver safety rating classification"
    - name: "coaching_required_flag"
      expr: coaching_required_flag
      comment: "Whether driver requires coaching intervention"
    - name: "hos_compliance_flag"
      expr: hos_compliance_flag
      comment: "Hours of Service compliance status"
    - name: "on_time_delivery_flag"
      expr: on_time_delivery_flag
      comment: "Whether delivery was on time"
    - name: "evaluation_period_month"
      expr: DATE_TRUNC('month', evaluation_period_start_date)
      comment: "Evaluation period start month for trend analysis"
  measures:
    - name: "avg_safety_score"
      expr: AVG(CAST(safety_score AS DOUBLE))
      comment: "Average driver safety score - critical for risk management and insurance"
    - name: "avg_eco_driving_score"
      expr: AVG(CAST(eco_driving_score AS DOUBLE))
      comment: "Average eco-driving score for sustainability and fuel cost reduction"
    - name: "avg_fuel_efficiency_km_per_liter"
      expr: AVG(CAST(fuel_efficiency_actual_km_per_liter AS DOUBLE))
      comment: "Average actual fuel efficiency achieved by drivers"
    - name: "avg_fuel_efficiency_variance_pct"
      expr: AVG(CAST(fuel_efficiency_variance_percent AS DOUBLE))
      comment: "Average variance from fuel efficiency benchmark - coaching opportunity indicator"
    - name: "total_distance_km"
      expr: SUM(CAST(total_distance_km AS DOUBLE))
      comment: "Total distance driven for workload analysis"
    - name: "total_driving_hours"
      expr: SUM(CAST(total_driving_time_hours AS DOUBLE))
      comment: "Total driving hours for capacity and fatigue management"
    - name: "total_co2_emissions_kg"
      expr: SUM(CAST(co2_emissions_kg AS DOUBLE))
      comment: "Total CO2 emissions attributed to driver behavior"
    - name: "avg_customer_feedback_score"
      expr: AVG(CAST(customer_feedback_score AS DOUBLE))
      comment: "Average customer feedback score for service quality measurement"
    - name: "distinct_drivers_evaluated"
      expr: COUNT(DISTINCT driver_profile_id)
      comment: "Number of distinct drivers evaluated in the period"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_incident`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Fleet incident metrics for safety management, risk assessment, and insurance cost control."
  source: "`transport_shipping_ecm`.`fleet`.`incident`"
  dimensions:
    - name: "incident_type"
      expr: incident_type
      comment: "Classification of the incident type"
    - name: "severity"
      expr: severity
      comment: "Severity level of the incident"
    - name: "incident_status"
      expr: incident_status
      comment: "Current status of the incident investigation/resolution"
    - name: "root_cause_category"
      expr: root_cause_category
      comment: "Root cause classification for prevention programs"
    - name: "location_country_code"
      expr: location_country_code
      comment: "Country where incident occurred for geographic risk analysis"
    - name: "dot_reportable_flag"
      expr: dot_reportable_flag
      comment: "Whether incident is DOT reportable for regulatory compliance"
    - name: "third_party_involved_flag"
      expr: third_party_involved_flag
      comment: "Whether third parties were involved for liability assessment"
    - name: "incident_month"
      expr: DATE_TRUNC('month', datetime)
      comment: "Month of incident occurrence for trend analysis"
  measures:
    - name: "total_incidents"
      expr: COUNT(1)
      comment: "Total number of fleet incidents - primary safety KPI"
    - name: "total_asset_damage_cost"
      expr: SUM(CAST(asset_damage_estimated_cost AS DOUBLE))
      comment: "Total estimated asset damage cost from incidents"
    - name: "total_cargo_damage_cost"
      expr: SUM(CAST(cargo_damage_estimated_cost AS DOUBLE))
      comment: "Total estimated cargo damage cost from incidents"
    - name: "distinct_assets_involved"
      expr: COUNT(DISTINCT transport_asset_id)
      comment: "Number of distinct assets involved in incidents"
    - name: "distinct_drivers_involved"
      expr: COUNT(DISTINCT driver_profile_id)
      comment: "Number of distinct drivers involved in incidents for targeted intervention"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_asset_assignment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Asset assignment metrics measuring fleet deployment efficiency, load utilisation, and operational performance."
  source: "`transport_shipping_ecm`.`fleet`.`asset_assignment`"
  dimensions:
    - name: "assignment_status"
      expr: assignment_status
      comment: "Current status of the asset assignment"
    - name: "assignment_type"
      expr: assignment_type
      comment: "Type of assignment for operational categorization"
    - name: "service_level"
      expr: service_level
      comment: "Service level of the assignment for SLA tracking"
    - name: "priority_level"
      expr: priority_level
      comment: "Priority level of the assignment"
    - name: "temperature_controlled_indicator"
      expr: temperature_controlled_indicator
      comment: "Whether assignment requires temperature control"
    - name: "hazmat_indicator"
      expr: hazmat_indicator
      comment: "Whether assignment involves hazardous materials"
    - name: "cross_border_indicator"
      expr: cross_border_indicator
      comment: "Whether assignment crosses international borders"
    - name: "planned_start_month"
      expr: DATE_TRUNC('month', planned_start_datetime)
      comment: "Planned start month for capacity planning analysis"
  measures:
    - name: "total_assignments"
      expr: COUNT(1)
      comment: "Total number of asset assignments for workload measurement"
    - name: "avg_load_utilization_pct"
      expr: AVG(CAST(load_utilization_percentage AS DOUBLE))
      comment: "Average load utilization percentage - key efficiency metric"
    - name: "total_distance_km"
      expr: SUM(CAST(distance_km AS DOUBLE))
      comment: "Total distance covered across all assignments"
    - name: "total_fuel_consumed_liters"
      expr: SUM(CAST(fuel_consumed_liters AS DOUBLE))
      comment: "Total fuel consumed across assignments"
    - name: "total_co2_emissions_kg"
      expr: SUM(CAST(co2_emissions_kg AS DOUBLE))
      comment: "Total CO2 emissions from assignments for sustainability tracking"
    - name: "total_cargo_weight_kg"
      expr: SUM(CAST(cargo_weight_kg AS DOUBLE))
      comment: "Total cargo weight transported"
    - name: "total_cargo_volume_cbm"
      expr: SUM(CAST(cargo_volume_cbm AS DOUBLE))
      comment: "Total cargo volume transported"
    - name: "avg_assignment_duration_hours"
      expr: AVG(CAST(assignment_duration_hours AS DOUBLE))
      comment: "Average assignment duration for planning and scheduling"
    - name: "total_assignment_cost"
      expr: SUM(CAST(assignment_cost_amount AS DOUBLE))
      comment: "Total cost of asset assignments for financial management"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_toll_record`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Toll expenditure metrics for route cost optimization and geographic cost analysis."
  source: "`transport_shipping_ecm`.`fleet`.`toll_record`"
  dimensions:
    - name: "toll_country_code"
      expr: toll_country_code
      comment: "Country of toll for geographic cost analysis"
    - name: "toll_operator_name"
      expr: toll_operator_name
      comment: "Toll operator for vendor management"
    - name: "payment_status"
      expr: payment_status
      comment: "Payment status of the toll record"
    - name: "vehicle_class"
      expr: vehicle_class
      comment: "Vehicle classification for toll rate analysis"
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the toll charge"
    - name: "transaction_month"
      expr: DATE_TRUNC('month', transaction_timestamp)
      comment: "Transaction month for trend analysis"
  measures:
    - name: "total_toll_amount"
      expr: SUM(CAST(total_toll_amount AS DOUBLE))
      comment: "Total toll expenditure - significant fleet operating cost"
    - name: "total_surcharge_amount"
      expr: SUM(CAST(surcharge_amount AS DOUBLE))
      comment: "Total surcharges on tolls"
    - name: "total_discount_amount"
      expr: SUM(CAST(discount_amount AS DOUBLE))
      comment: "Total discounts received on tolls for procurement effectiveness"
    - name: "total_tax_amount"
      expr: SUM(CAST(tax_amount AS DOUBLE))
      comment: "Total tax on toll charges"
    - name: "toll_transaction_count"
      expr: COUNT(1)
      comment: "Number of toll transactions for activity volume"
    - name: "avg_toll_per_transaction"
      expr: AVG(CAST(total_toll_amount AS DOUBLE))
      comment: "Average toll cost per transaction for route cost benchmarking"
    - name: "distinct_assets_tolled"
      expr: COUNT(DISTINCT transport_asset_id)
      comment: "Number of distinct assets incurring tolls"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_asset_cost_record`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Asset cost tracking metrics for total cost of ownership analysis, budget management, and cost category benchmarking."
  source: "`transport_shipping_ecm`.`fleet`.`asset_cost_record`"
  dimensions:
    - name: "cost_category"
      expr: cost_category
      comment: "Primary cost category for cost structure analysis"
    - name: "cost_subcategory"
      expr: cost_subcategory
      comment: "Detailed cost subcategory for granular analysis"
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of the cost record"
    - name: "payment_status"
      expr: payment_status
      comment: "Payment status for cash flow tracking"
    - name: "fiscal_year"
      expr: fiscal_year
      comment: "Fiscal year for budget period analysis"
    - name: "fiscal_period"
      expr: fiscal_period
      comment: "Fiscal period for budget tracking"
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the cost record"
    - name: "service_location_country"
      expr: service_location_country
      comment: "Country where service was performed for geographic cost analysis"
    - name: "cost_month"
      expr: DATE_TRUNC('month', cost_date)
      comment: "Cost date month for trend analysis"
  measures:
    - name: "total_cost_amount"
      expr: SUM(CAST(total_cost_amount AS DOUBLE))
      comment: "Total cost amount including tax for full cost visibility"
    - name: "total_base_cost"
      expr: SUM(CAST(cost_amount AS DOUBLE))
      comment: "Total base cost amount before tax"
    - name: "total_tax_amount"
      expr: SUM(CAST(tax_amount AS DOUBLE))
      comment: "Total tax on asset costs"
    - name: "avg_cost_per_record"
      expr: AVG(CAST(total_cost_amount AS DOUBLE))
      comment: "Average cost per record for benchmarking"
    - name: "distinct_assets_with_costs"
      expr: COUNT(DISTINCT transport_asset_id)
      comment: "Number of distinct assets incurring costs"
    - name: "cost_record_count"
      expr: COUNT(1)
      comment: "Number of cost records for activity tracking"
$$;

CREATE OR REPLACE VIEW `transport_shipping_ecm`.`_metrics`.`fleet_hos_log`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Hours of Service compliance metrics for regulatory adherence, driver fatigue management, and operational safety."
  source: "`transport_shipping_ecm`.`fleet`.`hos_log`"
  dimensions:
    - name: "duty_status"
      expr: duty_status
      comment: "Current duty status (driving, on-duty, sleeper berth, off-duty)"
    - name: "violation_flag"
      expr: violation_flag
      comment: "Whether an HOS violation occurred"
    - name: "violation_type"
      expr: violation_type
      comment: "Type of HOS violation for targeted compliance programs"
    - name: "violation_severity"
      expr: violation_severity
      comment: "Severity of the HOS violation"
    - name: "record_status"
      expr: record_status
      comment: "Status of the HOS log record"
    - name: "data_source"
      expr: data_source
      comment: "Source of HOS data (ELD, manual, etc.)"
    - name: "log_month"
      expr: DATE_TRUNC('month', log_date)
      comment: "Log date month for compliance trend analysis"
  measures:
    - name: "total_driving_hours"
      expr: SUM(CAST(driving_hours_day AS DOUBLE))
      comment: "Total driving hours logged for capacity and compliance analysis"
    - name: "total_on_duty_hours"
      expr: SUM(CAST(on_duty_hours_day AS DOUBLE))
      comment: "Total on-duty hours for workload analysis"
    - name: "total_distance_driven_miles"
      expr: SUM(CAST(distance_driven_miles AS DOUBLE))
      comment: "Total distance driven per HOS logs"
    - name: "avg_cycle_hours_70_8"
      expr: AVG(CAST(cycle_hours_70_8 AS DOUBLE))
      comment: "Average 70-hour/8-day cycle usage for fatigue risk assessment"
    - name: "hos_log_count"
      expr: COUNT(1)
      comment: "Total HOS log entries for compliance completeness tracking"
    - name: "distinct_drivers_logged"
      expr: COUNT(DISTINCT primary_hos_driver_profile_id)
      comment: "Number of distinct drivers with HOS logs"
$$;